import { resolveDeepLink, safeDeepLink } from './deeplink'
import {
  type PushReceivedMessage,
  type SubscriptionChangedMessage,
  SW_MESSAGE_PUSH_RECEIVED,
  SW_MESSAGE_SUBSCRIPTION_CHANGED,
} from './messages'
import { type NotificationContent, parsePushPayload } from './payload'
import type {
  ClientsLike,
  NotificationData,
  NotificationOptionsLike,
  PushSubscriptionLike,
  WindowClientLike,
} from './types'

/** Icon shown with every alert. The 192 px file is generated by `scripts/generate-icons.mjs`. */
export const NOTIFICATION_ICON = '/icon-192.png'

/** Options for `showNotification`. `renotify` stays false so a repeat with the same tag replaces the alert silently. */
export function buildNotificationOptions(content: NotificationContent, swVersion: string): NotificationOptionsLike {
  const options: NotificationOptionsLike = {
    body: content.body,
    tag: content.tag,
    renotify: false,
    icon: NOTIFICATION_ICON,
    lang: 'en-IN',
    data: { url: content.url, id: content.id, category: content.category, swVersion },
  }
  if (content.actions.length > 0) options.actions = content.actions.map((a) => ({ action: a.id, title: a.title }))
  return options
}

export interface PushDeps {
  show(title: string, options: NotificationOptionsLike): Promise<void>
  swVersion: string
  /** When given, open pages are told a push arrived so the inbox bell can refresh at once (W3.1). */
  clients?: ClientsLike
}

/**
 * Push: always shows exactly one notification, whatever the payload looks like. Then, best effort, open pages hear
 * that a push arrived (no content, only the fact); failing to tell them never undoes or delays the alert.
 */
export async function handlePush(deps: PushDeps, raw: string | null): Promise<void> {
  const { content } = parsePushPayload(raw)
  await deps.show(content.title, buildNotificationOptions(content, deps.swVersion))
  if (deps.clients) await postToPages(deps.clients, { type: SW_MESSAGE_PUSH_RECEIVED })
}

/** Reads the data the worker attached to a notification, trusting nothing: the link is checked again. */
export function readNotificationData(data: unknown): Pick<NotificationData, 'url'> {
  const url = typeof data === 'object' && data !== null ? (data as { url?: unknown }).url : undefined
  return { url: safeDeepLink(url) }
}

/** Which open tab to reuse: a same-origin tab, preferring the focused one, then a visible one, then any. */
export function chooseClient(clients: readonly WindowClientLike[], origin: string): WindowClientLike | null {
  const sameOrigin = clients.filter((client) => {
    try {
      return new URL(client.url).origin === origin
    } catch {
      return false
    }
  })
  return (
    sameOrigin.find((c) => c.focused) ??
    sameOrigin.find((c) => c.visibilityState === 'visible') ??
    sameOrigin[0] ??
    null
  )
}

export interface ClickDeps {
  clients: ClientsLike
  origin: string
}

export type ClickOutcome = 'focused' | 'navigated' | 'opened'

/**
 * Click: focus an open tab and send it to the link, or open a new window. The link is re-validated here even though
 * the push handler validated it, so a notification created by older code cannot open an arbitrary page.
 */
export async function handleNotificationClick(deps: ClickDeps, data: unknown): Promise<ClickOutcome> {
  const target = resolveDeepLink(readNotificationData(data).url, deps.origin)
  const open = async (): Promise<ClickOutcome> => {
    await deps.clients.openWindow(target)
    return 'opened'
  }

  const clients = await deps.clients.matchAll({ type: 'window', includeUncontrolled: true }).catch(() => null)
  if (!clients) return open()
  const client = chooseClient(clients, deps.origin)
  if (!client) return open()

  try {
    await client.focus()
    if (client.url === target) return 'focused'
    if (!client.navigate) return open()
    await client.navigate(target)
    return 'navigated'
  } catch {
    // focus() and navigate() can reject (tab closed meanwhile, browser policy). A new window always works.
    return open()
  }
}

export interface SubscriptionChangeDeps {
  /** Subscribes with the given key; resolves when the browser has a new subscription. */
  subscribe(key: BufferSource): Promise<unknown>
  /** Key to use when the browser did not hand us the old one (it is baked into the build). */
  fallbackKey: BufferSource | null
  clients: ClientsLike
}

export type ResubscribeOutcome = 'resubscribed' | 'no_key' | 'failed'

/**
 * `pushsubscriptionchange`: the browser rotated or dropped our subscription. Re-subscribe on a best-effort basis and
 * tell open pages. The worker has no sign-in, so it cannot tell the API; the page registers the new subscription
 * (see `usePushResync`), and a page opened later finds the same subscription and does the same.
 */
export async function handleSubscriptionChange(
  deps: SubscriptionChangeDeps,
  oldSubscription: PushSubscriptionLike | null | undefined,
): Promise<ResubscribeOutcome> {
  const key = oldSubscription?.options.applicationServerKey ?? deps.fallbackKey
  let outcome: ResubscribeOutcome = 'no_key'
  if (key) {
    try {
      await deps.subscribe(key)
      outcome = 'resubscribed'
    } catch {
      outcome = 'failed'
    }
  }
  await notifyPages(deps.clients, outcome === 'resubscribed')
  return outcome
}

async function notifyPages(clients: ClientsLike, resubscribed: boolean): Promise<void> {
  const message: SubscriptionChangedMessage = { type: SW_MESSAGE_SUBSCRIPTION_CHANGED, resubscribed }
  await postToPages(clients, message)
}

async function postToPages(clients: ClientsLike, message: SubscriptionChangedMessage | PushReceivedMessage) {
  try {
    const open = await clients.matchAll({ type: 'window', includeUncontrolled: true })
    for (const client of open) (client as WindowClientLike & { postMessage?(m: unknown): void }).postMessage?.(message)
  } catch {
    // no open page: the next visit picks the change up on its own
  }
}
