# Generated by Django 5.2.17 on 2026-10-06 07:59

import datetime
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.fields
import modules.notifications.domain.enums


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("web_push", "web_push"),
                            ("desktop_app", "desktop_app"),
                        ],
                        max_length=12,
                    ),
                ),
                ("endpoint_enc", core.fields.EncryptedTextField(blank=True, null=True)),
                (
                    "endpoint_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("p256dh_enc", core.fields.EncryptedTextField(blank=True, null=True)),
                ("auth_enc", core.fields.EncryptedTextField(blank=True, null=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "android"),
                            ("ios", "ios"),
                            ("windows", "windows"),
                            ("macos", "macos"),
                            ("linux", "linux"),
                            ("other", "other"),
                        ],
                        default=modules.notifications.domain.enums.DevicePlatform["OTHER"],
                        max_length=10,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        choices=[
                            ("chrome", "chrome"),
                            ("edge", "edge"),
                            ("firefox", "firefox"),
                            ("safari", "safari"),
                            ("other", "other"),
                        ],
                        default=modules.notifications.domain.enums.DeviceBrowser["OTHER"],
                        max_length=12,
                    ),
                ),
                (
                    "display_mode",
                    models.CharField(
                        choices=[
                            ("browser", "browser"),
                            ("standalone", "standalone"),
                            ("app", "app"),
                        ],
                        default=modules.notifications.domain.enums.DisplayMode["BROWSER"],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=80)),
                ("app_version", models.CharField(blank=True, max_length=20, null=True)),
                ("sw_version", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("first_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.SmallIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gone", "gone"),
                            ("failures", "failures"),
                            ("user_removed", "user_removed"),
                            ("signed_out", "signed_out"),
                            ("account_erased", "account_erased"),
                        ],
                        max_length=14,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_device",
                "indexes": [
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=["user_id"],
                        name="notif_device_active_idx",
                    ),
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", False)),
                        fields=["revoked_at"],
                        name="notif_device_revoked_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["web_push", "desktop_app"])),
                        name="notif_device_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "kind",
                                    modules.notifications.domain.enums.DeviceKind["WEB_PUSH"],
                                ),
                                _negated=True,
                            ),
                            models.Q(
                                ("auth_enc__isnull", False),
                                ("endpoint_enc__isnull", False),
                                ("endpoint_hash__isnull", False),
                                ("p256dh_enc__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="notif_device_web_push_keys",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("consecutive_failures__gte", 0)),
                        name="notif_device_failures",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("category", models.CharField(max_length=16)),
                ("event", models.CharField(max_length=24)),
                ("dedupe_key", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=80)),
                ("body", models.CharField(max_length=240)),
                ("deep_link", models.CharField(max_length=200)),
                ("tag", models.CharField(blank=True, max_length=80)),
                ("priority", models.SmallIntegerField()),
                ("context", models.JSONField(default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications_notification",
                "indexes": [
                    models.Index(fields=["user_id", "-created_at"], name="notif_inbox_idx"),
                    models.Index(
                        condition=models.Q(("read_at__isnull", True)),
                        fields=["user_id"],
                        name="notif_unread_idx",
                    ),
                    models.Index(fields=["created_at"], name="notif_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "dedupe_key"),
                        name="notif_notification_dedupe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("priority__gte", 0), ("priority__lte", 3)),
                        name="notif_notification_priority",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deep_link__startswith", "/"),
                            models.Q(("deep_link__startswith", "//"), _negated=True),
                        ),
                        name="notif_notification_link",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("push_master", models.BooleanField(default=True)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("quiet_enabled", models.BooleanField(default=True)),
                ("quiet_start", models.TimeField(default=datetime.time(22, 0))),
                ("quiet_end", models.TimeField(default=datetime.time(7, 0))),
                ("nudge_enabled", models.BooleanField(default=True)),
                ("nudge_time", models.TimeField(default=datetime.time(10, 0))),
                (
                    "nudge_tone",
                    models.CharField(
                        choices=[
                            ("calm", "calm"),
                            ("driven", "driven"),
                            ("celebratory", "celebratory"),
                        ],
                        default=modules.notifications.domain.enums.Tone["CALM"],
                        max_length=12,
                    ),
                ),
                ("next_nudge_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permission_state",
                    models.CharField(
                        choices=[
                            ("not_asked", "not_asked"),
                            ("pre_prompt_shown", "pre_prompt_shown"),
                            ("granted", "granted"),
                            ("denied", "denied"),
                            ("dismissed", "dismissed"),
                            ("skipped_install", "skipped_install"),
                            ("unsupported", "unsupported"),
                        ],
                        default=modules.notifications.domain.enums.PermissionState["NOT_ASKED"],
                        max_length=16,
                    ),
                ),
                (
                    "permission_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("onboarding", "onboarding"),
                            ("followup", "followup"),
                            ("settings", "settings"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("permission_decided_at", models.DateTimeField(blank=True, null=True)),
                ("permission_ask_count", models.SmallIntegerField(default=0)),
                ("last_asked_at", models.DateTimeField(blank=True, null=True)),
                ("digest_offered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications_settings",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("next_nudge_at__isnull", False),
                            ("nudge_enabled", True),
                            ("push_master", True),
                        ),
                        fields=["next_nudge_at"],
                        name="notif_settings_nudge_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("permission_ask_count__gte", 0),
                            ("permission_ask_count__lte", 3),
                        ),
                        name="notif_settings_asks",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quiet_start", models.F("quiet_end")), _negated=True),
                        name="notif_settings_quiet",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("nudge_tone__in", ["calm", "driven", "celebratory"])),
                        name="notif_settings_tone",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "permission_state__in",
                                [
                                    "not_asked",
                                    "pre_prompt_shown",
                                    "granted",
                                    "denied",
                                    "dismissed",
                                    "skipped_install",
                                    "unsupported",
                                ],
                            )
                        ),
                        name="notif_settings_permission",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("category", models.CharField(max_length=16)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("push", "push"),
                            ("email", "email"),
                            ("inbox", "inbox"),
                        ],
                        max_length=8,
                    ),
                ),
                ("enabled", models.BooleanField()),
            ],
            options={
                "db_table": "notifications_preference",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "category", "channel"),
                        name="notif_preference_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("channel__in", ["push", "email", "inbox"])),
                        name="notif_preference_channel",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("timer_end", "timer_end"),
                            ("stopwatch_long", "stopwatch_long"),
                            ("deliver_deferred", "deliver_deferred"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject_key", models.CharField(max_length=64)),
                ("expected_version", models.IntegerField(default=0)),
                ("fire_at", models.DateTimeField()),
                ("context", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("fired", "fired"),
                            ("skipped", "skipped"),
                            ("cancelled", "cancelled"),
                            ("failed", "failed"),
                        ],
                        default=modules.notifications.domain.enums.JobStatus["PENDING"],
                        max_length=10,
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("changed", "changed"),
                            ("paused", "paused"),
                            ("gone", "gone"),
                            ("flag_off", "flag_off"),
                            ("disabled", "disabled"),
                            ("stale", "stale"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=64, null=True)),
                ("attempts", models.SmallIntegerField(default=0)),
                ("fired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications_scheduledjob",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            (
                                "status",
                                modules.notifications.domain.enums.JobStatus["PENDING"],
                            )
                        ),
                        fields=["fire_at"],
                        name="notif_job_due_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            (
                                "status",
                                modules.notifications.domain.enums.JobStatus["PENDING"],
                            ),
                            _negated=True,
                        ),
                        fields=["updated_at"],
                        name="notif_job_prune_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "kind", "subject_key", "expected_version"),
                        name="notif_job_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["pending", "fired", "skipped", "cancelled", "failed"],
                            )
                        ),
                        name="notif_job_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                ["timer_end", "stopwatch_long", "deliver_deferred"],
                            )
                        ),
                        name="notif_job_kind",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("push", "push"),
                            ("email", "email"),
                            ("inbox", "inbox"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                            ("suppressed", "suppressed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "suppress_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("preference", "preference"),
                            ("quiet_hours", "quiet_hours"),
                            ("cap", "cap"),
                            ("no_device", "no_device"),
                            ("stale", "stale"),
                            ("visited_today", "visited_today"),
                            ("flag_off", "flag_off"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("counts_toward_cap", models.BooleanField(default=False)),
                ("http_status", models.SmallIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=40, null=True)),
                ("attempt", models.SmallIntegerField(default=1)),
                ("lateness_ms", models.IntegerField(blank=True, null=True)),
                (
                    "attempted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="notifications.device",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_delivery",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            (
                                "status",
                                modules.notifications.domain.enums.DeliveryStatus["SENT"],
                            )
                        ),
                        fields=["user_id", "-attempted_at"],
                        name="notif_delivery_sent_idx",
                    ),
                    models.Index(fields=["notification"], name="notif_delivery_notif_idx"),
                    models.Index(fields=["attempted_at"], name="notif_delivery_attempted_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notification", "channel", "device"),
                        name="notif_delivery_unique",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["queued", "sent", "failed", "suppressed"])),
                        name="notif_delivery_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "status",
                                    modules.notifications.domain.enums.DeliveryStatus["SUPPRESSED"],
                                ),
                                _negated=True,
                            ),
                            ("suppress_reason__isnull", False),
                            _connector="OR",
                        ),
                        name="notif_delivery_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt__gte", 1), ("attempt__lte", 3)),
                        name="notif_delivery_attempt",
                    ),
                ],
            },
        ),
    ]
