# Generated by Django 5.2.18 on 2026-10-07 03:31

import uuid

import django.db.models.deletion
from django.db import migrations, models

import modules.notifications.domain.enums


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.CharField(max_length=240)),
                ("attribution", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("calm", "calm"),
                            ("driven", "driven"),
                            ("celebratory", "celebratory"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("far", "far"),
                            ("near", "near"),
                            ("final_week", "final_week"),
                            ("exam_day", "exam_day"),
                            ("any", "any"),
                        ],
                        default=modules.notifications.domain.enums.MessagePhase["ANY"],
                        max_length=12,
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("published", "published"),
                            ("retired", "retired"),
                        ],
                        default=modules.notifications.domain.enums.MessageStatus["DRAFT"],
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seed_key",
                    models.CharField(blank=True, max_length=60, null=True, unique=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.course",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.level",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_message",
            },
        ),
        migrations.CreateModel(
            name="MessageShown",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("shown_on", models.DateField()),
                (
                    "channel",
                    models.CharField(choices=[("inapp", "inapp"), ("push", "push")], max_length=8),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shown",
                        to="notifications.message",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_messageshown",
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status", "tone", "phase"], name="ix_notif_message_pick"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("tone__in", ["calm", "driven", "celebratory"])),
                name="notif_message_tone",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("phase__in", ["far", "near", "final_week", "exam_day", "any"])),
                name="notif_message_phase",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "published", "retired"])),
                name="notif_message_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status",
                            modules.notifications.domain.enums.MessageStatus["PUBLISHED"],
                        ),
                        _negated=True,
                    ),
                    ("published_at__isnull", False),
                    _connector="OR",
                ),
                name="notif_message_published_at",
            ),
        ),
        migrations.AddIndex(
            model_name="messageshown",
            index=models.Index(fields=["shown_on"], name="notif_messageshown_prune_idx"),
        ),
        migrations.AddConstraint(
            model_name="messageshown",
            constraint=models.UniqueConstraint(fields=("user_id", "shown_on"), name="notif_messageshown_day"),
        ),
        migrations.AddConstraint(
            model_name="messageshown",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel__in", ["inapp", "push"])),
                name="notif_messageshown_channel",
            ),
        ),
    ]
