# Generated by Django 5.2.18 on 2026-10-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_motivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="next_weekly_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="suppress_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("preference", "preference"),
                    ("quiet_hours", "quiet_hours"),
                    ("cap", "cap"),
                    ("no_device", "no_device"),
                    ("stale", "stale"),
                    ("visited_today", "visited_today"),
                    ("flag_off", "flag_off"),
                    ("no_address", "no_address"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationsettings",
            index=models.Index(
                condition=models.Q(("next_weekly_at__isnull", False)),
                fields=["next_weekly_at"],
                name="notif_settings_weekly_idx",
            ),
        ),
    ]
