# Generated by Django 5.2.18 on 2026-10-07 08:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_weekly"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("timer_client_id", models.UUIDField()),
                ("timer_version", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pause", "pause"),
                            ("resume", "resume"),
                            ("start_break", "start_break"),
                            ("start_focus", "start_focus"),
                        ],
                        max_length=12,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_tokens",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_actiontoken",
                "indexes": [models.Index(fields=["expires_at"], name="notif_token_expiry_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                ["pause", "resume", "start_break", "start_focus"],
                            )
                        ),
                        name="notif_actiontoken_action",
                    )
                ],
            },
        ),
    ]
