# Generated by Django 5.2.18 on 2026-10-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_actiontoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="digest_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
