# Generated by Django 5.2.18 on 2026-10-07 17:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(max_length=32)),
                ("bucket", models.CharField(max_length=64)),
                ("path", models.CharField(max_length=512)),
                ("bytes", models.BigIntegerField()),
                ("mime", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("uploaded", "Uploaded"),
                            ("clean", "Clean"),
                            ("rejected", "Rejected"),
                            ("deleting", "Deleting"),
                        ],
                        default="reserved",
                        max_length=10,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, default="", max_length=32)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "media_attachment",
                "indexes": [
                    models.Index(fields=["user_id", "kind"], name="media_att_owner_kind_idx"),
                    models.Index(
                        condition=models.Q(("status", "reserved")),
                        fields=["expires_at"],
                        name="media_att_reservation_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("id", "user_id"), name="media_attachment_id_user_unique"),
                    models.UniqueConstraint(fields=("bucket", "path"), name="media_attachment_object_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("bytes__gte", 0)), name="media_attachment_bytes_nonnegative"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["reserved", "uploaded", "clean", "rejected", "deleting"])),
                        name="media_attachment_status_valid",
                    ),
                ],
            },
        ),
    ]
