# Generated by Django 5.2.17 on 2026-10-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "last_preset",
                    models.CharField(
                        choices=[("classic", "Classic"), ("deep", "Deep"), ("light", "Light"), ("custom", "Custom")],
                        default="classic",
                        max_length=7,
                    ),
                ),
                ("focus_minutes", models.SmallIntegerField(default=25)),
                ("short_break_minutes", models.SmallIntegerField(default=5)),
                ("long_break_minutes", models.SmallIntegerField(default=15)),
                ("rounds_before_long", models.SmallIntegerField(default=4)),
                ("auto_start_breaks", models.BooleanField(default=True)),
                ("auto_start_focus", models.BooleanField(default=False)),
                ("sound_enabled", models.BooleanField(default=True)),
                ("volume", models.SmallIntegerField(default=70)),
                ("notifications_enabled", models.BooleanField(default=False)),
                ("intro_seen", models.BooleanField(default=False)),
                ("cycle_id", models.UUIDField(blank=True, null=True)),
                ("cycle_round", models.SmallIntegerField(default=0)),
                (
                    "cycle_next_phase",
                    models.CharField(
                        choices=[("focus", "Focus"), ("short_break", "Short break"), ("long_break", "Long break")],
                        default="focus",
                        max_length=11,
                    ),
                ),
                ("cycle_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "focus_focussettings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("last_preset__in", ["classic", "deep", "light", "custom"])),
                        name="focus_settings_preset_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("focus_minutes__gte", 5), ("focus_minutes__lte", 120)),
                        name="focus_settings_focus_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("short_break_minutes__gte", 1), ("short_break_minutes__lte", 30)),
                        name="focus_settings_short_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("long_break_minutes__gte", 5), ("long_break_minutes__lte", 60)),
                        name="focus_settings_long_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rounds_before_long__gte", 2), ("rounds_before_long__lte", 8)),
                        name="focus_settings_rounds_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("volume__gte", 0), ("volume__lte", 100)), name="focus_settings_volume_range"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cycle_round__gte", 0), ("cycle_round__lte", 8)),
                        name="focus_settings_cycle_round",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cycle_next_phase__in", ["focus", "short_break", "long_break"])),
                        name="focus_settings_cycle_phase",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiveTimer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "phase",
                    models.CharField(
                        choices=[("focus", "Focus"), ("short_break", "Short break"), ("long_break", "Long break")],
                        max_length=11,
                    ),
                ),
                ("round_number", models.SmallIntegerField()),
                ("cycle_id", models.UUIDField()),
                ("planned_seconds", models.IntegerField()),
                ("extension_count", models.SmallIntegerField(default=0)),
                ("started_at", models.DateTimeField()),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("paused_total_seconds", models.IntegerField(default=0)),
                ("pause_count", models.SmallIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField()),
                ("away_pending", models.BooleanField(default=False)),
                (
                    "preset",
                    models.CharField(
                        choices=[("classic", "Classic"), ("deep", "Deep"), ("light", "Light"), ("custom", "Custom")],
                        default="classic",
                        max_length=7,
                    ),
                ),
                ("focus_minutes", models.SmallIntegerField()),
                ("short_break_minutes", models.SmallIntegerField()),
                ("long_break_minutes", models.SmallIntegerField()),
                ("rounds_before_long", models.SmallIntegerField()),
                ("auto_start_breaks", models.BooleanField(default=True)),
                ("auto_start_focus", models.BooleanField(default=False)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("reading", "reading"),
                            ("practice", "practice"),
                            ("revision", "revision"),
                            ("notes", "notes"),
                            ("mock_test", "mock_test"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("client_id", models.UUIDField()),
                ("version", models.IntegerField(default=1)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "db_table": "focus_activetimer",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("phase__in", ["focus", "short_break", "long_break"])),
                        name="focus_timer_phase_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("planned_seconds__gte", 60), ("planned_seconds__lte", 14400)),
                        name="focus_timer_planned_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("extension_count__gte", 0), ("extension_count__lte", 3)),
                        name="focus_timer_extension_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("paused_total_seconds__gte", 0)), name="focus_timer_pause_total"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("round_number__gte", 1), ("round_number__lte", 8)), name="focus_timer_round"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("away_pending", False), ("phase", "focus"), _connector="OR"),
                        name="focus_timer_away_only_focus",
                    ),
                ],
            },
        ),
    ]
