# Generated by Django 5.2.17 on 2026-10-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("focus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activetimer",
            name="overtime_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="focussettings",
            name="overtime_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
