# Generated by Django 5.2.18 on 2026-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("focus", "0002_overtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussettings",
            name="keep_awake",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="focussettings",
            name="keep_awake_in_breaks",
            field=models.BooleanField(default=False),
        ),
    ]
