# Generated by Django 5.2.18 on 2026-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("focus", "0003_keep_awake"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussettings",
            name="popout_on_start",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="focussettings",
            name="popout_prompt_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="focussettings",
            name="popout_size",
            field=models.CharField(choices=[("pill", "Pill"), ("card", "Card")], default="pill", max_length=4),
        ),
        migrations.AddConstraint(
            model_name="focussettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("popout_size__in", ["pill", "card"])), name="focus_settings_popout_size_valid"
            ),
        ),
    ]
