# Generated by Django 5.2.17 on 2026-10-05 10:28

import uuid

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="HourBucket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.UUIDField()),
                ("study_date", models.DateField()),
                ("hour", models.SmallIntegerField()),
                ("seconds", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tracking_hourbucket",
                "indexes": [models.Index(fields=["user_id", "study_date"], name="tracking_hour_day_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("user_id", "study_date", "hour"), name="tracking_hourbucket_key"),
                    models.CheckConstraint(
                        condition=models.Q(("hour__gte", 0), ("hour__lte", 23)), name="tracking_hourbucket_hour"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionAudit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("delete", "Delete"),
                            ("merge", "Merge"),
                            ("split", "Split"),
                            ("edit_times", "Edit times"),
                            ("manual_trim", "Manual trim"),
                        ],
                        max_length=12,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("session_count", models.SmallIntegerField(default=1)),
                ("undo_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tracking_sessionaudit",
                "indexes": [models.Index(fields=["user_id", "-created_at"], name="tracking_audit_user_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("action__in", ("delete", "merge", "split", "edit_times", "manual_trim"))),
                        name="tracking_audit_action_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackerSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("idle_minutes", models.SmallIntegerField(default=10)),
                ("week_start", models.SmallIntegerField(default=1)),
                (
                    "default_activity_type",
                    models.CharField(
                        choices=[
                            ("reading", "Reading"),
                            ("practice", "Practice"),
                            ("revision", "Revision"),
                            ("notes", "Notes"),
                            ("mock_test", "Mock test"),
                            ("other", "Other"),
                        ],
                        default="reading",
                        max_length=10,
                    ),
                ),
                ("tz", models.CharField(default="Asia/Kolkata", max_length=64)),
            ],
            options={
                "db_table": "tracking_trackersettings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("idle_minutes", 0),
                            models.Q(("idle_minutes__gte", 5), ("idle_minutes__lte", 60)),
                            _connector="OR",
                        ),
                        name="tracking_settings_idle_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("week_start__in", [0, 1])), name="tracking_settings_week_start"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "default_activity_type__in",
                                ["reading", "practice", "revision", "notes", "mock_test", "other"],
                            )
                        ),
                        name="tracking_settings_activity_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiveStopwatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField()),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("paused_total_seconds", models.IntegerField(default=0)),
                ("pause_count", models.SmallIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField()),
                ("last_active_at", models.DateTimeField()),
                ("idle_pending", models.BooleanField(default=False)),
                ("idle_prompted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("reading", "Reading"),
                            ("practice", "Practice"),
                            ("revision", "Revision"),
                            ("notes", "Notes"),
                            ("mock_test", "Mock test"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("client_id", models.UUIDField()),
                ("version", models.IntegerField(default=1)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_activestopwatch",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("activity_type__in", ["reading", "practice", "revision", "notes", "mock_test", "other"])
                        ),
                        name="tracking_stopwatch_activity_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("paused_total_seconds__gte", 0)), name="tracking_stopwatch_pause_total"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyRollup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.UUIDField()),
                ("study_date", models.DateField()),
                ("activity_type", models.CharField(max_length=10)),
                ("source", models.CharField(max_length=10)),
                ("verified", models.BooleanField(default=True)),
                ("seconds", models.IntegerField(default=0)),
                ("sessions", models.SmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.chapter",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_dailyrollup",
                "indexes": [
                    models.Index(fields=["user_id", "study_date"], name="tracking_rollup_day_idx"),
                    models.Index(fields=["user_id", "subject", "study_date"], name="tracking_rollup_subject_idx"),
                    models.Index(
                        condition=models.Q(("chapter__isnull", False)),
                        fields=["user_id", "chapter", "study_date"],
                        name="tracking_rollup_chapter_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user_id"),
                        models.F("study_date"),
                        django.db.models.functions.comparison.Coalesce(
                            "subject",
                            models.Value(
                                uuid.UUID("00000000-0000-0000-0000-000000000000"), output_field=models.UUIDField()
                            ),
                        ),
                        django.db.models.functions.comparison.Coalesce(
                            "chapter",
                            models.Value(
                                uuid.UUID("00000000-0000-0000-0000-000000000000"), output_field=models.UUIDField()
                            ),
                        ),
                        models.F("activity_type"),
                        models.F("source"),
                        models.F("verified"),
                        name="tracking_dailyrollup_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("period", models.CharField(choices=[("daily", "Daily"), ("weekly", "Weekly")], max_length=6)),
                ("subject_key", models.CharField(blank=True, default="", max_length=80)),
                ("target_minutes", models.IntegerField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_goal",
                "indexes": [
                    models.Index(fields=["user_id", "period", "-effective_from"], name="tracking_goal_lookup_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("period__in", ("daily", "weekly"))), name="tracking_goal_period_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("period", "daily"), ("target_minutes__gte", 15), ("target_minutes__lte", 1440)),
                            models.Q(("period", "weekly"), ("target_minutes__gte", 30), ("target_minutes__lte", 10080)),
                            _connector="OR",
                        ),
                        name="tracking_goal_target_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="tracking_goal_dates_ordered",
                    ),
                    models.UniqueConstraint(
                        models.F("user_id"),
                        models.F("period"),
                        models.F("subject_key"),
                        condition=models.Q(("effective_to__isnull", True)),
                        name="tracking_goal_one_open",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("client_id", models.UUIDField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pomodoro", "Pomodoro"),
                            ("stopwatch", "Stopwatch"),
                            ("manual", "Manual"),
                            ("auto", "Auto"),
                        ],
                        default="pomodoro",
                        max_length=10,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("reading", "Reading"),
                            ("practice", "Practice"),
                            ("revision", "Revision"),
                            ("notes", "Notes"),
                            ("mock_test", "Mock test"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("partial", "Partial")], default="completed", max_length=10
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("planned_seconds", models.IntegerField(blank=True, null=True)),
                ("focus_seconds", models.IntegerField()),
                ("paused_total_seconds", models.IntegerField(default=0)),
                ("pause_count", models.SmallIntegerField(default=0)),
                ("round_number", models.SmallIntegerField(blank=True, null=True)),
                ("cycle_id", models.UUIDField(blank=True, null=True)),
                ("interruption_reason", models.CharField(blank=True, default="", max_length=12)),
                ("auto_closed", models.BooleanField(default=False)),
                ("presence_verified", models.BooleanField(default=True)),
                ("study_date", models.DateField()),
                ("tz", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("is_edited", models.BooleanField(default=False)),
                ("edit_count", models.SmallIntegerField(default=0)),
                ("original_started_at", models.DateTimeField(blank=True, null=True)),
                ("original_ended_at", models.DateTimeField(blank=True, null=True)),
                ("overlaps_other", models.BooleanField(default=False)),
                ("merged_count", models.SmallIntegerField(default=1)),
                ("idle_trimmed", models.BooleanField(default=False)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_sessions",
                        to="syllabus.chapter",
                    ),
                ),
                (
                    "split_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="split_parts",
                        to="tracking.studysession",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_sessions",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_studysession",
                "indexes": [
                    models.Index(fields=["user_id", "-study_date"], name="tracking_session_day_idx"),
                    models.Index(fields=["user_id", "-started_at"], name="tracking_session_started_idx"),
                    models.Index(fields=["user_id", "subject", "-started_at"], name="tracking_session_subject_idx"),
                    models.Index(fields=["user_id", "chapter"], name="tracking_session_chapter_idx"),
                    models.Index(fields=["user_id", "source", "-started_at"], name="tracking_session_source_idx"),
                    models.Index(fields=["user_id", "study_date", "started_at"], name="tracking_session_overlap_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("client_id__isnull", False)),
                        fields=("user_id", "client_id"),
                        name="tracking_studysession_client_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("focus_seconds__gte", 60),
                            ("focus_seconds__lte", 86400),
                            models.Q(
                                ("source__in", ["manual", "auto"]), ("focus_seconds__lte", 43200), _connector="OR"
                            ),
                        ),
                        name="tracking_studysession_focus_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ended_at__gte", models.F("started_at"))),
                        name="tracking_studysession_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("completed", "partial"))),
                        name="tracking_studysession_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source__in", ["pomodoro", "stopwatch", "manual", "auto"])),
                        name="tracking_studysession_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("activity_type__in", ["reading", "practice", "revision", "notes", "mock_test", "other"])
                        ),
                        name="tracking_studysession_activity_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("interruption_reason", ""), ("status", "partial"), _connector="OR"),
                        name="tracking_studysession_reason_partial",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status", "completed"), ("source", "pomodoro"), _connector="OR"),
                        name="tracking_studysession_partial_pomodoro",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source", "pomodoro"),
                            models.Q(("round_number__isnull", True), ("cycle_id__isnull", True)),
                            _connector="OR",
                        ),
                        name="tracking_studysession_round_pomodoro",
                    ),
                ],
            },
        ),
    ]
