# Generated by Django 5.2.17 on 2026-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackersettings",
            name="auto_capture_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
