/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as CoursesCourseIndexRouteImport } from './routes/courses.$course.index'
import { Route as CoursesCourseLevelRouteImport } from './routes/courses.$course.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIndexRoute = CoursesCourseIndexRouteImport.update({
  id: '/courses/$course/',
  path: '/courses/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseLevelRoute = CoursesCourseLevelRouteImport.update({
  id: '/courses/$course/$level',
  path: '/courses/$course/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/courses/$course/$level': typeof CoursesCourseLevelRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/courses/$course/$level': typeof CoursesCourseLevelRoute
  '/courses/$course': typeof CoursesCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/courses/$course/$level': typeof CoursesCourseLevelRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/design-system'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/features/$slug'
    | '/courses/'
    | '/features/'
    | '/courses/$course/$level'
    | '/courses/$course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/design-system'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/features/$slug'
    | '/courses'
    | '/features'
    | '/courses/$course/$level'
    | '/courses/$course'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/design-system'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/features/$slug'
    | '/courses/'
    | '/features/'
    | '/courses/$course/$level'
    | '/courses/$course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  CoursesCourseLevelRoute: typeof CoursesCourseLevelRoute
  CoursesCourseIndexRoute: typeof CoursesCourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/': {
      id: '/courses/$course/'
      path: '/courses/$course'
      fullPath: '/courses/$course/'
      preLoaderRoute: typeof CoursesCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/$level': {
      id: '/courses/$course/$level'
      path: '/courses/$course/$level'
      fullPath: '/courses/$course/$level'
      preLoaderRoute: typeof CoursesCourseLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  CoursesCourseLevelRoute: CoursesCourseLevelRoute,
  CoursesCourseIndexRoute: CoursesCourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
