/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppRevisionRouteImport } from './routes/app.revision'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as AppSettingsCoverageRouteImport } from './routes/app.settings.coverage'
import { Route as AppSettingsTrackerRouteImport } from './routes/app.settings.tracker'
import { Route as AppSyllabusIndexRouteImport } from './routes/app.syllabus.index'
import { Route as AppTrackerIndexRouteImport } from './routes/app.tracker.index'
import { Route as AppTrackerGoalsRouteImport } from './routes/app.tracker.goals'
import { Route as AppTrackerLogRouteImport } from './routes/app.tracker.log'
import { Route as AppTrackerReportsRouteImport } from './routes/app.tracker.reports'
import { Route as CoursesCourseIndexRouteImport } from './routes/courses.$course.index'
import { Route as OgCoursesCourseRouteImport } from './routes/og.courses.$course'
import { Route as AppSyllabusSubjectIndexRouteImport } from './routes/app.syllabus.$subject.index'
import { Route as AppSyllabusSubjectChapterRouteImport } from './routes/app.syllabus.$subject.$chapter'
import { Route as AppTrackerDayDateRouteImport } from './routes/app.tracker.day.$date'
import { Route as CoursesCourseLevelIndexRouteImport } from './routes/courses.$course.$level.index'
import { Route as CoursesCourseLevelSubjectIndexRouteImport } from './routes/courses.$course.$level.$subject.index'
import { Route as CoursesCourseLevelSubjectChapterRouteImport } from './routes/courses.$course.$level.$subject.$chapter'
import { Route as OgCoursesCourseLevelSubjectChapterRouteImport } from './routes/og.courses.$course.$level.$subject.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppRevisionRoute = AppRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsCoverageRoute = AppSettingsCoverageRouteImport.update({
  id: '/settings/coverage',
  path: '/settings/coverage',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTrackerRoute = AppSettingsTrackerRouteImport.update({
  id: '/settings/tracker',
  path: '/settings/tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppSyllabusIndexRoute = AppSyllabusIndexRouteImport.update({
  id: '/syllabus/',
  path: '/syllabus/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackerIndexRoute = AppTrackerIndexRouteImport.update({
  id: '/tracker/',
  path: '/tracker/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackerGoalsRoute = AppTrackerGoalsRouteImport.update({
  id: '/tracker/goals',
  path: '/tracker/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackerLogRoute = AppTrackerLogRouteImport.update({
  id: '/tracker/log',
  path: '/tracker/log',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackerReportsRoute = AppTrackerReportsRouteImport.update({
  id: '/tracker/reports',
  path: '/tracker/reports',
  getParentRoute: () => AppRoute,
} as any)
const CoursesCourseIndexRoute = CoursesCourseIndexRouteImport.update({
  id: '/courses/$course/',
  path: '/courses/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgCoursesCourseRoute = OgCoursesCourseRouteImport.update({
  id: '/og/courses/$course',
  path: '/og/courses/$course',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSyllabusSubjectIndexRoute = AppSyllabusSubjectIndexRouteImport.update({
  id: '/syllabus/$subject/',
  path: '/syllabus/$subject/',
  getParentRoute: () => AppRoute,
} as any)
const AppSyllabusSubjectChapterRoute =
  AppSyllabusSubjectChapterRouteImport.update({
    id: '/syllabus/$subject/$chapter',
    path: '/syllabus/$subject/$chapter',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackerDayDateRoute = AppTrackerDayDateRouteImport.update({
  id: '/tracker/day/$date',
  path: '/tracker/day/$date',
  getParentRoute: () => AppRoute,
} as any)
const CoursesCourseLevelIndexRoute = CoursesCourseLevelIndexRouteImport.update({
  id: '/courses/$course/$level/',
  path: '/courses/$course/$level/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseLevelSubjectIndexRoute =
  CoursesCourseLevelSubjectIndexRouteImport.update({
    id: '/courses/$course/$level/$subject/',
    path: '/courses/$course/$level/$subject/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseLevelSubjectChapterRoute =
  CoursesCourseLevelSubjectChapterRouteImport.update({
    id: '/courses/$course/$level/$subject/$chapter',
    path: '/courses/$course/$level/$subject/$chapter',
    getParentRoute: () => rootRouteImport,
  } as any)
const OgCoursesCourseLevelSubjectChapterRoute =
  OgCoursesCourseLevelSubjectChapterRouteImport.update({
    id: '/$level/$subject/$chapter',
    path: '/$level/$subject/$chapter',
    getParentRoute: () => OgCoursesCourseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/account': typeof AppAccountRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/revision': typeof AppRevisionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/app/': typeof AppIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/app/settings/coverage': typeof AppSettingsCoverageRoute
  '/app/settings/tracker': typeof AppSettingsTrackerRoute
  '/app/tracker/goals': typeof AppTrackerGoalsRoute
  '/app/tracker/log': typeof AppTrackerLogRoute
  '/app/tracker/reports': typeof AppTrackerReportsRoute
  '/og/courses/$course': typeof OgCoursesCourseRouteWithChildren
  '/app/syllabus/': typeof AppSyllabusIndexRoute
  '/app/tracker/': typeof AppTrackerIndexRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
  '/app/syllabus/$subject/$chapter': typeof AppSyllabusSubjectChapterRoute
  '/app/tracker/day/$date': typeof AppTrackerDayDateRoute
  '/app/syllabus/$subject/': typeof AppSyllabusSubjectIndexRoute
  '/courses/$course/$level/': typeof CoursesCourseLevelIndexRoute
  '/courses/$course/$level/$subject/$chapter': typeof CoursesCourseLevelSubjectChapterRoute
  '/courses/$course/$level/$subject/': typeof CoursesCourseLevelSubjectIndexRoute
  '/og/courses/$course/$level/$subject/$chapter': typeof OgCoursesCourseLevelSubjectChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/account': typeof AppAccountRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/revision': typeof AppRevisionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/app': typeof AppIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/app/settings/coverage': typeof AppSettingsCoverageRoute
  '/app/settings/tracker': typeof AppSettingsTrackerRoute
  '/app/tracker/goals': typeof AppTrackerGoalsRoute
  '/app/tracker/log': typeof AppTrackerLogRoute
  '/app/tracker/reports': typeof AppTrackerReportsRoute
  '/og/courses/$course': typeof OgCoursesCourseRouteWithChildren
  '/app/syllabus': typeof AppSyllabusIndexRoute
  '/app/tracker': typeof AppTrackerIndexRoute
  '/courses/$course': typeof CoursesCourseIndexRoute
  '/app/syllabus/$subject/$chapter': typeof AppSyllabusSubjectChapterRoute
  '/app/tracker/day/$date': typeof AppTrackerDayDateRoute
  '/app/syllabus/$subject': typeof AppSyllabusSubjectIndexRoute
  '/courses/$course/$level': typeof CoursesCourseLevelIndexRoute
  '/courses/$course/$level/$subject/$chapter': typeof CoursesCourseLevelSubjectChapterRoute
  '/courses/$course/$level/$subject': typeof CoursesCourseLevelSubjectIndexRoute
  '/og/courses/$course/$level/$subject/$chapter': typeof OgCoursesCourseLevelSubjectChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/account': typeof AppAccountRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/revision': typeof AppRevisionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/app/': typeof AppIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/app/settings/coverage': typeof AppSettingsCoverageRoute
  '/app/settings/tracker': typeof AppSettingsTrackerRoute
  '/app/tracker/goals': typeof AppTrackerGoalsRoute
  '/app/tracker/log': typeof AppTrackerLogRoute
  '/app/tracker/reports': typeof AppTrackerReportsRoute
  '/og/courses/$course': typeof OgCoursesCourseRouteWithChildren
  '/app/syllabus/': typeof AppSyllabusIndexRoute
  '/app/tracker/': typeof AppTrackerIndexRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
  '/app/syllabus/$subject/$chapter': typeof AppSyllabusSubjectChapterRoute
  '/app/tracker/day/$date': typeof AppTrackerDayDateRoute
  '/app/syllabus/$subject/': typeof AppSyllabusSubjectIndexRoute
  '/courses/$course/$level/': typeof CoursesCourseLevelIndexRoute
  '/courses/$course/$level/$subject/$chapter': typeof CoursesCourseLevelSubjectChapterRoute
  '/courses/$course/$level/$subject/': typeof CoursesCourseLevelSubjectIndexRoute
  '/og/courses/$course/$level/$subject/$chapter': typeof OgCoursesCourseLevelSubjectChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/design-system'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/app/account'
    | '/app/onboarding'
    | '/app/revision'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/features/$slug'
    | '/app/'
    | '/courses/'
    | '/features/'
    | '/app/settings/coverage'
    | '/app/settings/tracker'
    | '/app/tracker/goals'
    | '/app/tracker/log'
    | '/app/tracker/reports'
    | '/og/courses/$course'
    | '/app/syllabus/'
    | '/app/tracker/'
    | '/courses/$course/'
    | '/app/syllabus/$subject/$chapter'
    | '/app/tracker/day/$date'
    | '/app/syllabus/$subject/'
    | '/courses/$course/$level/'
    | '/courses/$course/$level/$subject/$chapter'
    | '/courses/$course/$level/$subject/'
    | '/og/courses/$course/$level/$subject/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/app/account'
    | '/app/onboarding'
    | '/app/revision'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/features/$slug'
    | '/app'
    | '/courses'
    | '/features'
    | '/app/settings/coverage'
    | '/app/settings/tracker'
    | '/app/tracker/goals'
    | '/app/tracker/log'
    | '/app/tracker/reports'
    | '/og/courses/$course'
    | '/app/syllabus'
    | '/app/tracker'
    | '/courses/$course'
    | '/app/syllabus/$subject/$chapter'
    | '/app/tracker/day/$date'
    | '/app/syllabus/$subject'
    | '/courses/$course/$level'
    | '/courses/$course/$level/$subject/$chapter'
    | '/courses/$course/$level/$subject'
    | '/og/courses/$course/$level/$subject/$chapter'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/design-system'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/app/account'
    | '/app/onboarding'
    | '/app/revision'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/features/$slug'
    | '/app/'
    | '/courses/'
    | '/features/'
    | '/app/settings/coverage'
    | '/app/settings/tracker'
    | '/app/tracker/goals'
    | '/app/tracker/log'
    | '/app/tracker/reports'
    | '/og/courses/$course'
    | '/app/syllabus/'
    | '/app/tracker/'
    | '/courses/$course/'
    | '/app/syllabus/$subject/$chapter'
    | '/app/tracker/day/$date'
    | '/app/syllabus/$subject/'
    | '/courses/$course/$level/'
    | '/courses/$course/$level/$subject/$chapter'
    | '/courses/$course/$level/$subject/'
    | '/og/courses/$course/$level/$subject/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  OgCoursesCourseRoute: typeof OgCoursesCourseRouteWithChildren
  CoursesCourseIndexRoute: typeof CoursesCourseIndexRoute
  CoursesCourseLevelIndexRoute: typeof CoursesCourseLevelIndexRoute
  CoursesCourseLevelSubjectChapterRoute: typeof CoursesCourseLevelSubjectChapterRoute
  CoursesCourseLevelSubjectIndexRoute: typeof CoursesCourseLevelSubjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/revision': {
      id: '/app/revision'
      path: '/revision'
      fullPath: '/app/revision'
      preLoaderRoute: typeof AppRevisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/coverage': {
      id: '/app/settings/coverage'
      path: '/settings/coverage'
      fullPath: '/app/settings/coverage'
      preLoaderRoute: typeof AppSettingsCoverageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/tracker': {
      id: '/app/settings/tracker'
      path: '/settings/tracker'
      fullPath: '/app/settings/tracker'
      preLoaderRoute: typeof AppSettingsTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/syllabus/': {
      id: '/app/syllabus/'
      path: '/syllabus'
      fullPath: '/app/syllabus/'
      preLoaderRoute: typeof AppSyllabusIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracker/': {
      id: '/app/tracker/'
      path: '/tracker'
      fullPath: '/app/tracker/'
      preLoaderRoute: typeof AppTrackerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracker/goals': {
      id: '/app/tracker/goals'
      path: '/tracker/goals'
      fullPath: '/app/tracker/goals'
      preLoaderRoute: typeof AppTrackerGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracker/log': {
      id: '/app/tracker/log'
      path: '/tracker/log'
      fullPath: '/app/tracker/log'
      preLoaderRoute: typeof AppTrackerLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracker/reports': {
      id: '/app/tracker/reports'
      path: '/tracker/reports'
      fullPath: '/app/tracker/reports'
      preLoaderRoute: typeof AppTrackerReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/courses/$course/': {
      id: '/courses/$course/'
      path: '/courses/$course'
      fullPath: '/courses/$course/'
      preLoaderRoute: typeof CoursesCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/courses/$course': {
      id: '/og/courses/$course'
      path: '/og/courses/$course'
      fullPath: '/og/courses/$course'
      preLoaderRoute: typeof OgCoursesCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/syllabus/$subject/': {
      id: '/app/syllabus/$subject/'
      path: '/syllabus/$subject'
      fullPath: '/app/syllabus/$subject/'
      preLoaderRoute: typeof AppSyllabusSubjectIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/syllabus/$subject/$chapter': {
      id: '/app/syllabus/$subject/$chapter'
      path: '/syllabus/$subject/$chapter'
      fullPath: '/app/syllabus/$subject/$chapter'
      preLoaderRoute: typeof AppSyllabusSubjectChapterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracker/day/$date': {
      id: '/app/tracker/day/$date'
      path: '/tracker/day/$date'
      fullPath: '/app/tracker/day/$date'
      preLoaderRoute: typeof AppTrackerDayDateRouteImport
      parentRoute: typeof AppRoute
    }
    '/courses/$course/$level/': {
      id: '/courses/$course/$level/'
      path: '/courses/$course/$level'
      fullPath: '/courses/$course/$level/'
      preLoaderRoute: typeof CoursesCourseLevelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/$level/$subject/': {
      id: '/courses/$course/$level/$subject/'
      path: '/courses/$course/$level/$subject'
      fullPath: '/courses/$course/$level/$subject/'
      preLoaderRoute: typeof CoursesCourseLevelSubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/$level/$subject/$chapter': {
      id: '/courses/$course/$level/$subject/$chapter'
      path: '/courses/$course/$level/$subject/$chapter'
      fullPath: '/courses/$course/$level/$subject/$chapter'
      preLoaderRoute: typeof CoursesCourseLevelSubjectChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/courses/$course/$level/$subject/$chapter': {
      id: '/og/courses/$course/$level/$subject/$chapter'
      path: '/$level/$subject/$chapter'
      fullPath: '/og/courses/$course/$level/$subject/$chapter'
      preLoaderRoute: typeof OgCoursesCourseLevelSubjectChapterRouteImport
      parentRoute: typeof OgCoursesCourseRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRevisionRoute: typeof AppRevisionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsCoverageRoute: typeof AppSettingsCoverageRoute
  AppSettingsTrackerRoute: typeof AppSettingsTrackerRoute
  AppTrackerGoalsRoute: typeof AppTrackerGoalsRoute
  AppTrackerLogRoute: typeof AppTrackerLogRoute
  AppTrackerReportsRoute: typeof AppTrackerReportsRoute
  AppSyllabusIndexRoute: typeof AppSyllabusIndexRoute
  AppTrackerIndexRoute: typeof AppTrackerIndexRoute
  AppSyllabusSubjectChapterRoute: typeof AppSyllabusSubjectChapterRoute
  AppTrackerDayDateRoute: typeof AppTrackerDayDateRoute
  AppSyllabusSubjectIndexRoute: typeof AppSyllabusSubjectIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRevisionRoute: AppRevisionRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsCoverageRoute: AppSettingsCoverageRoute,
  AppSettingsTrackerRoute: AppSettingsTrackerRoute,
  AppTrackerGoalsRoute: AppTrackerGoalsRoute,
  AppTrackerLogRoute: AppTrackerLogRoute,
  AppTrackerReportsRoute: AppTrackerReportsRoute,
  AppSyllabusIndexRoute: AppSyllabusIndexRoute,
  AppTrackerIndexRoute: AppTrackerIndexRoute,
  AppSyllabusSubjectChapterRoute: AppSyllabusSubjectChapterRoute,
  AppTrackerDayDateRoute: AppTrackerDayDateRoute,
  AppSyllabusSubjectIndexRoute: AppSyllabusSubjectIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OgCoursesCourseRouteChildren {
  OgCoursesCourseLevelSubjectChapterRoute: typeof OgCoursesCourseLevelSubjectChapterRoute
}

const OgCoursesCourseRouteChildren: OgCoursesCourseRouteChildren = {
  OgCoursesCourseLevelSubjectChapterRoute:
    OgCoursesCourseLevelSubjectChapterRoute,
}

const OgCoursesCourseRouteWithChildren = OgCoursesCourseRoute._addFileChildren(
  OgCoursesCourseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  OgCoursesCourseRoute: OgCoursesCourseRouteWithChildren,
  CoursesCourseIndexRoute: CoursesCourseIndexRoute,
  CoursesCourseLevelIndexRoute: CoursesCourseLevelIndexRoute,
  CoursesCourseLevelSubjectChapterRoute: CoursesCourseLevelSubjectChapterRoute,
  CoursesCourseLevelSubjectIndexRoute: CoursesCourseLevelSubjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
