# Generated by Django 5.2.17 on 2026-10-04 18:34

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("institute_name", models.CharField(max_length=120)),
                ("institute_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "syllabus_course",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExamTerm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=60)),
                ("exam_start", models.DateField(blank=True, null=True)),
                ("exam_end", models.DateField(blank=True, null=True)),
                ("is_open", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms",
                        to="syllabus.course",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_examterm",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=32)),
                ("name", models.CharField(max_length=80)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="levels",
                        to="syllabus.course",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_level",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "from_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.examterm",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schemes",
                        to="syllabus.level",
                    ),
                ),
                (
                    "to_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.examterm",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_scheme",
                "ordering": ["level", "-code"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("paper_number", models.SmallIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("total_marks", models.SmallIntegerField(blank=True, null=True)),
                (
                    "exam_duration_minutes",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("theory", "Theory"),
                            ("practical", "Practical"),
                            ("mixed", "Mixed"),
                            ("elective", "Elective"),
                        ],
                        default="theory",
                        max_length=12,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="syllabus.scheme",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_subject",
                "ordering": ["sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=240)),
                (
                    "marks_min",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "marks_max",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "weight_source",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("analysis", "Analysis based"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("target_practice_sets", models.SmallIntegerField(default=1)),
                ("target_revisions", models.SmallIntegerField(default=2)),
                ("target_mocks", models.SmallIntegerField(default=1)),
                ("est_study_minutes", models.SmallIntegerField(blank=True, null=True)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_chapter",
                "ordering": ["sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="SyllabusGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.SmallIntegerField(default=0)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="syllabus.scheme",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_group",
                "ordering": ["sort_order", "key"],
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="syllabus.syllabusgroup",
            ),
        ),
        migrations.CreateModel(
            name="SyllabusReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("level", "Level"),
                            ("scheme", "Scheme"),
                            ("subject", "Subject"),
                            ("chapter", "Chapter"),
                            ("topic", "Topic"),
                        ],
                        max_length=10,
                    ),
                ),
                ("node_id", models.UUIDField()),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("message", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("fixed", "Fixed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_report",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="syllabus_report_queue_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=240)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("section", "Section"),
                            ("rule", "Rule"),
                            ("standard", "Standard"),
                            ("formula", "Formula"),
                            ("case_law", "Case law"),
                            ("illustration", "Illustration"),
                        ],
                        default="concept",
                        max_length=14,
                    ),
                ),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="syllabus.chapter",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_topic",
                "ordering": ["sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="ChapterMap",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("same", "Same"),
                            ("split", "Split"),
                            ("merged", "Merged"),
                            ("partial", "Partial"),
                        ],
                        default="same",
                        max_length=10,
                    ),
                ),
                (
                    "carry_ratio",
                    models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=3),
                ),
                (
                    "from_chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps_out",
                        to="syllabus.chapter",
                    ),
                ),
                (
                    "to_chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps_in",
                        to="syllabus.chapter",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_chaptermap",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_chapter", "to_chapter"),
                        name="syllabus_chaptermap_unique_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("relation__in", ["same", "split", "merged", "partial"])),
                        name="syllabus_chaptermap_relation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("carry_ratio__gte", 0), ("carry_ratio__lte", 1)),
                        name="syllabus_chaptermap_ratio_range",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="examterm",
            constraint=models.UniqueConstraint(fields=("course", "code"), name="syllabus_examterm_unique_code"),
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.UniqueConstraint(fields=("course", "code"), name="syllabus_level_unique_code"),
        ),
        migrations.AddConstraint(
            model_name="scheme",
            constraint=models.UniqueConstraint(fields=("level", "code"), name="syllabus_scheme_unique_code"),
        ),
        migrations.AddConstraint(
            model_name="scheme",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "published", "retired"])),
                name="syllabus_scheme_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(fields=("subject", "key"), name="syllabus_chapter_unique_key"),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("marks_min__isnull", True),
                    ("marks_max__isnull", True),
                    ("marks_max__gte", models.F("marks_min")),
                    _connector="OR",
                ),
                name="syllabus_chapter_marks_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_practice_sets__gte", 0),
                    ("target_practice_sets__lte", 20),
                    ("target_revisions__gte", 0),
                    ("target_revisions__lte", 20),
                    ("target_mocks__gte", 0),
                    ("target_mocks__lte", 20),
                ),
                name="syllabus_chapter_targets_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabusgroup",
            constraint=models.UniqueConstraint(fields=("scheme", "key"), name="syllabus_group_unique_key"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["scheme", "group", "sort_order"],
                name="syllabus_subject_tree_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(fields=("scheme", "key"), name="syllabus_subject_unique_key"),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["theory", "practical", "mixed", "elective"])),
                name="syllabus_subject_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(fields=("chapter", "key"), name="syllabus_topic_unique_key"),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "concept",
                            "section",
                            "rule",
                            "standard",
                            "formula",
                            "case_law",
                            "illustration",
                        ],
                    )
                ),
                name="syllabus_topic_kind_valid",
            ),
        ),
    ]
