# Generated by Django 5.2.17 on 2026-10-04 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0002_seed_reference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheme",
            options={
                "ordering": ["level", "-code"],
                "permissions": [("publish_scheme", "Can publish and retire schemes")],
            },
        ),
    ]
