# Generated by Django 5.2.17 on 2026-10-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0003_scheme_publish_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="section",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="subject",
            name="source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
