# Generated by Django 5.2.17 on 2026-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0008_examterm_level_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaptermap",
            name="basis",
            field=models.CharField(
                choices=[
                    ("key", "Same key"),
                    ("name", "Same name"),
                    ("fuzzy", "Similar name"),
                    ("renamed", "Renamed in place"),
                    ("moved", "Moved to another paper"),
                    ("split", "Proposed split"),
                    ("merge", "Proposed merge"),
                    ("manual", "Added by an editor"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chaptermap",
            name="confidence",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="chaptermap",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="chaptermap",
            index=models.Index(fields=["needs_review"], name="syllabus_chaptermap_review_idx"),
        ),
        migrations.AddConstraint(
            model_name="chaptermap",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("basis__in", ["key", "name", "fuzzy", "renamed", "moved", "split", "merge", "manual"])
                ),
                name="syllabus_chaptermap_basis_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaptermap",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                    _connector="OR",
                ),
                name="syllabus_chaptermap_confidence_range",
            ),
        ),
    ]
