# Generated by Django 5.2.18 on 2026-10-08 19:17

import uuid

import django.db.models.deletion
from django.db import migrations, models

from core.migration_utils import postgres_only


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecallDeck",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=8)),
                ("owner_user_id", models.UUIDField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("status", models.CharField(default="active", max_length=10)),
                ("card_count", models.IntegerField(default=0)),
                ("client_id", models.UUIDField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.course",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.level",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "db_table": "recall_deck",
            },
        ),
        migrations.CreateModel(
            name="RecallDeckVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_no", models.IntegerField()),
                ("state", models.CharField(default="draft", max_length=12)),
                ("changelog_md", models.TextField(blank=True, default="")),
                ("item_count", models.SmallIntegerField(default=0)),
                ("tier_counts", models.JSONField(blank=True, default=dict)),
                ("diff_summary", models.JSONField(blank=True, default=dict)),
                ("published_by", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="recall.recalldeck"
                    ),
                ),
            ],
            options={
                "db_table": "recall_deckversion",
            },
        ),
        migrations.AddField(
            model_name="recalldeck",
            name="draft_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="recall.recalldeckversion",
            ),
        ),
        migrations.AddField(
            model_name="recalldeck",
            name="live_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="recall.recalldeckversion",
            ),
        ),
        migrations.CreateModel(
            name="RecallItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=16)),
                ("ownership", models.CharField(max_length=8)),
                ("owner_user_id", models.UUIDField(blank=True, null=True)),
                ("origin", models.CharField(default="manual", max_length=24)),
                ("status", models.CharField(default="active", max_length=10)),
                ("importance", models.CharField(default="bullet", max_length=10)),
                ("subject_key", models.CharField(blank=True, max_length=80, null=True)),
                ("chapter_key", models.CharField(blank=True, max_length=100, null=True)),
                ("reference_keys", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("rights_status", models.CharField(default="unknown", max_length=24)),
                ("source_label", models.CharField(blank=True, default="", max_length=200)),
                ("source_url", models.URLField(blank=True, max_length=500, null=True)),
                ("origin_module", models.CharField(blank=True, max_length=16, null=True)),
                ("origin_ref", models.CharField(blank=True, max_length=80, null=True)),
                ("origin_kind", models.CharField(blank=True, max_length=16, null=True)),
                ("origin_locator", models.JSONField(blank=True, null=True)),
                ("origin_dangling", models.BooleanField(default=False)),
                ("shareable", models.BooleanField(default=False)),
                ("shareable_attested_at", models.DateTimeField(blank=True, null=True)),
                ("needs_editor_check", models.BooleanField(default=False)),
                ("check_reason", models.CharField(blank=True, max_length=12, null=True)),
                ("check_ref", models.CharField(blank=True, max_length=80, null=True)),
                ("fingerprint", models.CharField(max_length=64)),
                ("search_text", models.TextField(blank=True, default="")),
                ("external_ref", models.CharField(blank=True, max_length=160, null=True)),
                ("client_id", models.UUIDField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.course",
                    ),
                ),
                (
                    "forked_from_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recall.recallitem",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.level",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.scheme",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="syllabus.topic",
                    ),
                ),
            ],
            options={
                "db_table": "recall_item",
            },
        ),
        migrations.CreateModel(
            name="RecallDeckItem",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "deck_id", "item_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.SmallIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="members", to="recall.recalldeck"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="recall.recallitem"
                    ),
                ),
            ],
            options={
                "db_table": "recall_deckitem",
            },
        ),
        migrations.CreateModel(
            name="RecallItemVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_no", models.IntegerField()),
                ("state", models.CharField(default="draft", max_length=12)),
                ("change_kind", models.CharField(default="create", max_length=12)),
                ("change_note", models.TextField(blank=True, default="")),
                ("fields", models.JSONField()),
                ("fields_schema", models.SmallIntegerField(default=1)),
                ("cloze_count", models.SmallIntegerField(default=0)),
                ("content_hash", models.CharField(max_length=64)),
                ("plain_text", models.TextField(blank=True, default="")),
                ("authored_by", models.UUIDField(blank=True, null=True)),
                ("live_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="recall.recallitem"
                    ),
                ),
            ],
            options={
                "db_table": "recall_itemversion",
            },
        ),
        migrations.AddField(
            model_name="recallitem",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="recall.recallitemversion",
            ),
        ),
        migrations.AddField(
            model_name="recallitem",
            name="live_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="recall.recallitemversion",
            ),
        ),
        migrations.CreateModel(
            name="RecallDeckVersionItem",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "deck_version_id", "item_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.SmallIntegerField(default=0)),
                ("change_vs_prev", models.CharField(default="unchanged", max_length=12)),
                (
                    "deck_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="recall.recalldeckversion"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="recall.recallitem"
                    ),
                ),
                (
                    "item_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="recall.recallitemversion"
                    ),
                ),
            ],
            options={
                "db_table": "recall_deckversionitem",
            },
        ),
        migrations.AddConstraint(
            model_name="recalldeckversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["draft", "in_review", "live", "superseded", "withdrawn"])),
                name="recall_deckversion_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recalldeckversion",
            constraint=models.UniqueConstraint(fields=("deck", "version_no"), name="recall_deckversion_no_uniq"),
        ),
        migrations.AddConstraint(
            model_name="recalldeckversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "live")), fields=("deck",), name="recall_deckversion_one_live"
            ),
        ),
        migrations.AddIndex(
            model_name="recalldeck",
            index=models.Index(fields=["kind", "status", "chapter"], name="recall_deck_library_idx"),
        ),
        migrations.AddIndex(
            model_name="recalldeck",
            index=models.Index(
                condition=models.Q(("kind", "user")),
                fields=["owner_user_id", "status", "-updated_at"],
                name="recall_deck_mine_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recalldeck",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["platform", "user"])), name="recall_deck_kind_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="recalldeck",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived", "withdrawn"])), name="recall_deck_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="recalldeck",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "platform"), ("owner_user_id__isnull", True)),
                    models.Q(("kind", "user"), ("owner_user_id__isnull", False)),
                    _connector="OR",
                ),
                name="recall_deck_owner_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="recalldeck",
            constraint=models.CheckConstraint(
                condition=models.Q(("card_count__gte", 0)), name="recall_deck_card_count_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="recalldeck",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)), fields=("slug",), name="recall_deck_slug_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="recalldeck",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False), ("owner_user_id__isnull", False)),
                fields=("owner_user_id", "client_id"),
                name="recall_deck_client_id_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="recalldeckitem",
            index=models.Index(fields=["item"], name="recall_deckitem_item_idx"),
        ),
        migrations.AddConstraint(
            model_name="recallitemversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["draft", "live", "superseded", "withdrawn"])),
                name="recall_itemversion_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitemversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("change_kind__in", ["create", "typo", "clarify", "substantive", "amendment"])),
                name="recall_itemversion_change_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitemversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("cloze_count__gte", 0), ("cloze_count__lte", 20)),
                name="recall_itemversion_cloze_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitemversion",
            constraint=models.UniqueConstraint(fields=("item", "version_no"), name="recall_itemversion_no_uniq"),
        ),
        migrations.AddConstraint(
            model_name="recallitemversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "live")), fields=("item",), name="recall_itemversion_one_live"
            ),
        ),
        migrations.AddIndex(
            model_name="recallitem",
            index=models.Index(
                condition=models.Q(("ownership", "user")),
                fields=["owner_user_id", "status", "-updated_at"],
                name="recall_item_mine_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recallitem",
            index=models.Index(
                condition=models.Q(("ownership", "platform"), ("status", "active")),
                fields=["chapter", "importance", "id"],
                name="recall_item_library_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recallitem",
            index=models.Index(
                condition=models.Q(("ownership", "user")),
                fields=["owner_user_id", "fingerprint"],
                name="recall_item_dupes_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recallitem",
            index=models.Index(
                condition=models.Q(("forked_from_item__isnull", False)),
                fields=["forked_from_item"],
                name="recall_item_fork_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recallitem",
            index=models.Index(
                condition=models.Q(("needs_editor_check", True)),
                fields=["needs_editor_check"],
                name="recall_item_check_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["pointer", "formula", "section", "definition", "mnemonic", "case_law", "cloze"])
                ),
                name="recall_item_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("ownership__in", ["platform", "user"])), name="recall_item_ownership_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "origin__in",
                        [
                            "manual",
                            "selection",
                            "solution",
                            "mistake",
                            "ai_suggestion",
                            "import_csv",
                            "import_share",
                            "editor",
                            "fork",
                            "amendment_card",
                            "material_item",
                            "super50_entry",
                        ],
                    )
                ),
                name="recall_item_origin_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived", "withdrawn", "deleted"])),
                name="recall_item_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("importance__in", ["bullet", "important", "mandatory"])),
                name="recall_item_importance_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rights_status__in",
                        ["original", "licensed", "institute_material", "third_party_claimed", "unknown"],
                    )
                ),
                name="recall_item_rights_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("owner_user_id__isnull", True), ("ownership", "platform")),
                    models.Q(("owner_user_id__isnull", False), ("ownership", "user")),
                    _connector="OR",
                ),
                name="recall_item_owner_matches_ownership",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("chapter__isnull", True),
                    models.Q(("chapter_key__isnull", False), ("subject_key__isnull", False)),
                    _connector="OR",
                ),
                name="recall_item_chapter_has_keys",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("fingerprint__regex", "^[0-9a-f]{64}$")), name="recall_item_fingerprint_hex"
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_ref__isnull", False)),
                fields=("external_ref",),
                name="recall_item_external_ref_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False), ("owner_user_id__isnull", False)),
                fields=("owner_user_id", "client_id"),
                name="recall_item_client_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("origin_kind__isnull", False),
                    ("origin_ref__isnull", False),
                    ("status__in", ["active", "archived"]),
                ),
                fields=("owner_user_id", "origin_module", "origin_ref", "origin_kind"),
                name="recall_item_source_kind_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="recalldeckversionitem",
            index=models.Index(fields=["item"], name="recall_dvi_item_idx"),
        ),
        migrations.AddConstraint(
            model_name="recalldeckversionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("change_vs_prev__in", ["added", "unchanged", "typo", "clarify", "substantive", "amendment"])
                ),
                name="recall_deckversionitem_change_valid",
            ),
        ),
        # PostgreSQL only: containment indexes for the two searched JSON lists, and the stored full-text column (ERD 2.1)
        postgres_only(
            [
                "CREATE INDEX recall_item_refkeys_gin ON recall_item USING gin (reference_keys jsonb_path_ops)",
                "CREATE INDEX recall_item_tags_gin ON recall_item USING gin (tags jsonb_path_ops)",
                "ALTER TABLE recall_item ADD COLUMN search_tsv tsvector "
                "GENERATED ALWAYS AS (to_tsvector('english', search_text)) STORED",
                "CREATE INDEX recall_item_search_gin ON recall_item USING gin (search_tsv)",
            ],
            [
                "DROP INDEX IF EXISTS recall_item_search_gin",
                "ALTER TABLE recall_item DROP COLUMN IF EXISTS search_tsv",
                "DROP INDEX IF EXISTS recall_item_tags_gin",
                "DROP INDEX IF EXISTS recall_item_refkeys_gin",
            ],
        ),
    ]
