# Generated by Django 5.2.18 on 2026-10-08 19:17

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models

import modules.recall.models
from core.migration_utils import composite_fks, postgres_only

# Frozen copies: a later change of the defaults is a new `recall_params` row, never an edit of this one. A test compares
# them with the py-fsrs defaults.
FSRS6_DEFAULT_WEIGHTS = [
    0.212, 1.2931, 2.3065, 8.2956, 6.4133, 0.8334, 3.0194, 0.001, 1.8722, 0.1666, 0.796,
    1.4835, 0.0614, 0.2629, 1.6483, 0.6014, 1.8729, 0.5425, 0.0912, 0.0658, 0.1542,
]  # fmt: skip

# PRD 8.3. `pro` is seeded and unused until billing exists.
QUOTA_PLANS = {
    "free": {
        "max_cards": 1500, "max_cards_per_deck": 500, "max_decks": 100, "max_active_shares": 20,
        "ai_suggestions_per_day": 30, "ai_batches_per_day": 3, "share_imports_per_day": 30, "pack_size": 300,
    },
    "pro": {
        "max_cards": 20000, "max_cards_per_deck": 2000, "max_decks": 500, "max_active_shares": 100,
        "ai_suggestions_per_day": 150, "ai_batches_per_day": 15, "share_imports_per_day": 100, "pack_size": 500,
    },
}  # fmt: skip


def seed(apps, schema_editor):
    Params = apps.get_model("recall", "RecallParams")
    Params.objects.get_or_create(
        scope="default",
        scheduler_version="fsrs-6.0",
        status="active",
        defaults={"weights": FSRS6_DEFAULT_WEIGHTS, "optimiser": "py-fsrs defaults"},
    )
    Plan = apps.get_model("recall", "RecallQuotaPlan")
    for code, limits in QUOTA_PLANS.items():
        Plan.objects.get_or_create(plan_code=code, defaults=limits)


class Migration(migrations.Migration):
    dependencies = [
        ("recall", "0001_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecallQuotaPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_code", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("max_cards", models.IntegerField()),
                ("max_cards_per_deck", models.IntegerField()),
                ("max_decks", models.IntegerField()),
                ("max_active_shares", models.IntegerField()),
                ("ai_suggestions_per_day", models.IntegerField()),
                ("ai_batches_per_day", models.IntegerField()),
                ("share_imports_per_day", models.IntegerField()),
                ("pack_size", models.IntegerField()),
            ],
            options={
                "db_table": "recall_quotaplan",
            },
        ),
        migrations.CreateModel(
            name="RecallParams",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scope", models.CharField(max_length=8)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("scheduler_version", models.CharField(default="fsrs-6.0", max_length=16)),
                ("weights", models.JSONField()),
                ("status", models.CharField(default="active", max_length=10)),
                ("n_reviews", models.IntegerField(blank=True, null=True)),
                ("n_cards", models.IntegerField(blank=True, null=True)),
                ("fitted_from", models.DateTimeField(blank=True, null=True)),
                ("fitted_to", models.DateTimeField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("optimiser", models.CharField(blank=True, max_length=80, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "recall_params",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("scope__in", ["default", "user", "pooled"])),
                        name="recall_params_scope_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "candidate", "retired", "rejected"])),
                        name="recall_params_status_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "default"), ("status", "active")),
                        fields=("scheduler_version",),
                        name="recall_params_one_default",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "user"), ("status", "active")),
                        fields=("user_id",),
                        name="recall_params_one_per_user",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecallCard",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("ordinal", models.SmallIntegerField(default=0)),
                ("chapter_id", models.UUIDField(blank=True, null=True)),
                ("subject_key", models.CharField(blank=True, max_length=80, null=True)),
                ("importance", models.SmallIntegerField(default=0)),
                ("state", models.SmallIntegerField(default=0)),
                ("step", models.SmallIntegerField(blank=True, null=True)),
                ("stability", models.FloatField(blank=True, null=True)),
                ("difficulty", models.FloatField(blank=True, null=True)),
                ("due_scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("postponed_until", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("last_review_at", models.DateTimeField(blank=True, null=True)),
                ("reps", models.IntegerField(default=0)),
                ("lapses", models.IntegerField(default=0)),
                ("last_lapse_at", models.DateTimeField(blank=True, null=True)),
                ("leech", models.BooleanField(default=False)),
                ("status", models.CharField(default="active", max_length=10)),
                ("suspend_reason", models.CharField(blank=True, max_length=8, null=True)),
                ("buried_until", models.DateTimeField(blank=True, null=True)),
                ("needs_recheck", models.BooleanField(default=False)),
                ("recheck_reason", models.CharField(blank=True, max_length=16, null=True)),
                ("recheck_ref", models.CharField(blank=True, max_length=80, null=True)),
                ("scheduler_version", models.CharField(default="fsrs-6.0", max_length=16)),
                ("rev", models.IntegerField(default=1)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="cards", to="recall.recallitem"
                    ),
                ),
                (
                    "item_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="recall.recallitemversion"
                    ),
                ),
                (
                    "params",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recall.recallparams",
                    ),
                ),
            ],
            options={
                "db_table": "recall_card",
            },
        ),
        migrations.CreateModel(
            name="RecallQuotaUsage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("cards_active", models.IntegerField(default=0)),
                ("decks_active", models.IntegerField(default=0)),
                ("shares_active", models.IntegerField(default=0)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "recall_quotausage",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cards_active__gte", 0), ("decks_active__gte", 0), ("shares_active__gte", 0)
                        ),
                        name="recall_quotausage_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecallScheduleEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("kind", models.CharField(max_length=14)),
                ("at", models.DateTimeField()),
                ("from_due", models.DateTimeField(blank=True, null=True)),
                ("to_due", models.DateTimeField(blank=True, null=True)),
                ("stability_before", models.FloatField(blank=True, null=True)),
                ("stability_after", models.FloatField(blank=True, null=True)),
                ("reason_code", models.CharField(blank=True, default="", max_length=14)),
                ("ref", models.CharField(blank=True, max_length=80, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_events",
                        to="recall.recallcard",
                    ),
                ),
            ],
            options={
                "db_table": "recall_scheduleevent",
            },
        ),
        migrations.CreateModel(
            name="RecallSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("client_id", models.UUIDField()),
                ("source", models.CharField(max_length=14)),
                ("spec", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="open", max_length=12)),
                ("started_at", models.DateTimeField()),
                ("last_event_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("tz", models.CharField(max_length=64)),
                ("local_date", models.DateField()),
                ("planned_count", models.SmallIntegerField(default=0)),
                ("reviewed", models.IntegerField(default=0)),
                ("new_count", models.IntegerField(default=0)),
                ("again", models.IntegerField(default=0)),
                ("hard", models.IntegerField(default=0)),
                ("good", models.IntegerField(default=0)),
                ("easy", models.IntegerField(default=0)),
                ("active_seconds", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "recall_session",
                "indexes": [
                    models.Index(fields=["user_id", "-started_at"], name="recall_session_recent_idx"),
                    models.Index(
                        condition=models.Q(("status", "open")),
                        fields=["status", "last_event_at"],
                        name="recall_session_open_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source__in",
                                ["today", "chapter", "deck", "forgotten", "quick", "catchup", "cram", "review_ahead"],
                            )
                        ),
                        name="recall_session_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["open", "closed", "auto_closed"])),
                        name="recall_session_status_valid",
                    ),
                    models.UniqueConstraint(fields=("user_id", "client_id"), name="recall_session_client_uniq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecallSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("desired_retention", models.DecimalField(decimal_places=2, default=Decimal("0.90"), max_digits=3)),
                ("new_per_day", models.SmallIntegerField(default=10)),
                ("reviews_per_day", models.SmallIntegerField(default=100)),
                ("learning_steps_min", models.JSONField(default=modules.recall.models.default_learning_steps)),
                ("relearning_steps_min", models.JSONField(default=modules.recall.models.default_relearning_steps)),
                ("max_interval_days", models.IntegerField(default=365)),
                ("leech_threshold", models.SmallIntegerField(default=8)),
                ("day_start_hour", models.SmallIntegerField(default=4)),
                ("tz", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("bury_siblings", models.BooleanField(default=True)),
                ("interleave", models.BooleanField(default=True)),
                ("catchup_mode", models.CharField(default="auto", max_length=8)),
                ("pause_new_in_catchup", models.BooleanField(default=True)),
                ("exam_horizon", models.BooleanField(default=True)),
                ("recall_counts_as_revision", models.BooleanField(default=True)),
                ("gestures", models.BooleanField(default=True)),
                ("show_intervals", models.BooleanField(default=True)),
                ("quick_minutes_per_day", models.SmallIntegerField(default=30)),
                ("vacation_until", models.DateField(blank=True, null=True)),
                ("improve_scheduler_consent", models.BooleanField(default=False)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "params",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recall.recallparams",
                    ),
                ),
            ],
            options={
                "db_table": "recall_settings",
            },
        ),
        migrations.CreateModel(
            name="RecallSubscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("follow_updates", models.BooleanField(default=True)),
                ("unlock_mode", models.CharField(default="with_coverage", max_length=14)),
                ("min_importance", models.CharField(default="bullet", max_length=10)),
                ("status", models.CharField(default="active", max_length=10)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="recall.recalldeck",
                    ),
                ),
                (
                    "pending_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recall.recalldeckversion",
                    ),
                ),
                (
                    "pinned_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="recall.recalldeckversion"
                    ),
                ),
                (
                    "synced_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="recall.recalldeckversion"
                    ),
                ),
            ],
            options={
                "db_table": "recall_subscription",
            },
        ),
        migrations.AddField(
            model_name="recallcard",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to="recall.recallsubscription",
            ),
        ),
        migrations.AddIndex(
            model_name="recallscheduleevent",
            index=models.Index(fields=["user_id", "card", "at"], name="recall_schedev_card_idx"),
        ),
        migrations.AddConstraint(
            model_name="recallscheduleevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "content_reset",
                            "forget",
                            "postpone",
                            "unpostpone",
                            "horizon",
                            "manual_due",
                            "suspend",
                            "unsuspend",
                        ],
                    )
                ),
                name="recall_scheduleevent_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallscheduleevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason_code__in",
                        [
                            "",
                            "typo_free",
                            "substantive",
                            "amendment",
                            "rebalance",
                            "vacation",
                            "student",
                            "exam_horizon",
                            "parked",
                        ],
                    )
                ),
                name="recall_scheduleevent_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("desired_retention__gte", "0.80"), ("desired_retention__lte", "0.97")),
                name="recall_settings_retention_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_per_day__gte", 0), ("new_per_day__lte", 100)), name="recall_settings_new_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("reviews_per_day__gte", 20), ("reviews_per_day__lte", 500)),
                name="recall_settings_reviews_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_interval_days__gte", 30), ("max_interval_days__lte", 3650)),
                name="recall_settings_interval_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("leech_threshold__gte", 4), ("leech_threshold__lte", 20)),
                name="recall_settings_leech_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_start_hour__gte", 0), ("day_start_hour__lte", 6)),
                name="recall_settings_day_start_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("quick_minutes_per_day__gte", 5), ("quick_minutes_per_day__lte", 240)),
                name="recall_settings_quick_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsettings",
            constraint=models.CheckConstraint(
                condition=models.Q(("catchup_mode__in", ["auto", "off", "on"])), name="recall_settings_catchup_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="recallsubscription",
            index=models.Index(fields=["deck", "follow_updates", "status"], name="recall_sub_sync_idx"),
        ),
        migrations.AddIndex(
            model_name="recallsubscription",
            index=models.Index(fields=["user_id", "status"], name="recall_sub_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="recallsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("unlock_mode__in", ["with_coverage", "all"])),
                name="recall_subscription_unlock_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived"])), name="recall_subscription_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_importance__in", ["bullet", "important", "mandatory"])),
                name="recall_subscription_tier_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallsubscription",
            constraint=models.UniqueConstraint(fields=("user_id", "deck"), name="recall_subscription_user_deck_uniq"),
        ),
        migrations.AddIndex(
            model_name="recallcard",
            index=models.Index(
                condition=models.Q(("state__gt", 0), ("status", "active")),
                fields=["user_id", "due_at"],
                name="recall_card_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recallcard",
            index=models.Index(
                condition=models.Q(("state", 0), ("status", "active")),
                fields=["user_id", "-importance", "created_at"],
                name="recall_card_new_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recallcard",
            index=models.Index(fields=["user_id", "chapter_id", "status"], name="recall_card_chapter_idx"),
        ),
        migrations.AddIndex(
            model_name="recallcard",
            index=models.Index(
                condition=models.Q(("lapses__gt", 0), ("status", "active")),
                fields=["user_id", "-last_lapse_at"],
                name="recall_card_forgotten_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recallcard",
            index=models.Index(
                condition=models.Q(("needs_recheck", True)),
                fields=["user_id", "needs_recheck"],
                name="recall_card_recheck_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recallcard",
            index=models.Index(fields=["item"], name="recall_card_item_idx"),
        ),
        migrations.AddIndex(
            model_name="recallcard",
            index=models.Index(
                condition=models.Q(("subscription__isnull", False)), fields=["subscription"], name="recall_card_sub_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.UniqueConstraint(
                fields=("user_id", "item", "ordinal"), name="recall_card_user_item_ordinal_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.UniqueConstraint(fields=("id", "user_id"), name="recall_card_id_user_uniq"),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "suspended", "archived", "deleted"])),
                name="recall_card_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__gte", 0), ("state__lte", 3)), name="recall_card_state_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.CheckConstraint(
                condition=models.Q(("importance__gte", 0), ("importance__lte", 2)), name="recall_card_importance_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("difficulty__isnull", True),
                    models.Q(("difficulty__gte", 1), ("difficulty__lte", 10)),
                    _connector="OR",
                ),
                name="recall_card_difficulty_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.CheckConstraint(
                condition=models.Q(("stability__isnull", True), ("stability__gt", 0), _connector="OR"),
                name="recall_card_stability_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("stability__isnull", True), ("state", 0)),
                    models.Q(("stability__isnull", False), ("state__gt", 0)),
                    _connector="OR",
                ),
                name="recall_card_new_iff_no_stability",
            ),
        ),
        migrations.AddConstraint(
            model_name="recallcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("due_at__isnull", True), ("state", 0)),
                    models.Q(("due_at__isnull", False), ("state__gt", 0)),
                    _connector="OR",
                ),
                name="recall_card_new_iff_no_due",
            ),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
        # PostgreSQL only: the weights list has exactly 21 numbers, and an event belongs to a card of the same student
        postgres_only(
            [
                "ALTER TABLE recall_params ADD CONSTRAINT recall_params_weights_len "
                "CHECK (scheduler_version <> 'fsrs-6.0' OR jsonb_array_length(weights) = 21)"
            ],
            ["ALTER TABLE recall_params DROP CONSTRAINT IF EXISTS recall_params_weights_len"],
        ),
        composite_fks(
            (
                "recall_scheduleevent",
                "recall_scheduleevent_card_user_fk",
                ("card_id", "user_id"),
                "recall_card",
                ("id", "user_id"),
            )
        ),
    ]
