# Generated by Django 5.2.18 on 2026-10-08 19:17

from django.db import migrations, models

from .. import reviewlog_sql


def create_table(apps, schema_editor):
    for statement in reviewlog_sql.create_statements(schema_editor.connection.vendor):
        schema_editor.execute(statement)


def drop_table(apps, schema_editor):
    for statement in reviewlog_sql.drop_statements(schema_editor.connection.vendor):
        schema_editor.execute(statement)


class Migration(migrations.Migration):
    dependencies = [
        ("recall", "0002_student_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecallReviewLog",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("id", models.UUIDField()),
                ("kind", models.CharField(default="review", max_length=8)),
                ("card_id", models.UUIDField()),
                ("item_id", models.UUIDField()),
                ("item_version_id", models.UUIDField()),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("rating", models.SmallIntegerField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("mode", models.CharField(default="normal", max_length=16)),
                ("counts_for_scheduling", models.BooleanField(default=True)),
                ("device_id", models.CharField(blank=True, max_length=64, null=True)),
                ("tz_offset_min", models.SmallIntegerField(default=0)),
                ("local_date", models.DateField()),
                ("voids_id", models.UUIDField(blank=True, null=True)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("phase_before", models.SmallIntegerField(blank=True, null=True)),
                ("stability_before", models.FloatField(blank=True, null=True)),
                ("difficulty_before", models.FloatField(blank=True, null=True)),
                ("elapsed_days", models.IntegerField(blank=True, null=True)),
                ("retrievability_before", models.FloatField(blank=True, null=True)),
                ("phase_after", models.SmallIntegerField(blank=True, null=True)),
                ("stability_after", models.FloatField(blank=True, null=True)),
                ("difficulty_after", models.FloatField(blank=True, null=True)),
                ("scheduled_days", models.FloatField(blank=True, null=True)),
                ("due_after", models.DateTimeField(blank=True, null=True)),
                ("params_id", models.UUIDField(blank=True, null=True)),
                ("scheduler_version", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "db_table": "recall_reviewlog",
                "managed": False,
            },
        ),
        migrations.RunPython(create_table, drop_table),
    ]
