# Generated by Django 5.2.18 on 2026-10-08 19:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recall", "0003_reviewlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecallDailyRollup",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "local_date", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("local_date", models.DateField()),
                ("new_cards", models.IntegerField(default=0)),
                ("learn_reviews", models.IntegerField(default=0)),
                ("review_reviews", models.IntegerField(default=0)),
                ("relearn_reviews", models.IntegerField(default=0)),
                ("again", models.IntegerField(default=0)),
                ("hard", models.IntegerField(default=0)),
                ("good", models.IntegerField(default=0)),
                ("easy", models.IntegerField(default=0)),
                ("mandatory_reviews", models.IntegerField(default=0)),
                ("seconds", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recall_dailyrollup",
            },
        ),
        migrations.CreateModel(
            name="RecallAuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("action", models.CharField(max_length=20)),
                ("target_kind", models.CharField(max_length=16)),
                ("target_id", models.CharField(max_length=80)),
                ("detail", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "recall_auditlog",
                "indexes": [
                    models.Index(fields=["target_kind", "target_id", "created_at"], name="recall_audit_target_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                [
                                    "deck_publish",
                                    "item_withdraw",
                                    "share_takedown",
                                    "attest_own_words",
                                    "params_activate",
                                    "force_replay",
                                    "quota_change",
                                ],
                            )
                        ),
                        name="recall_auditlog_action_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecallChapterRollup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("local_date", models.DateField()),
                ("chapter_id", models.UUIDField(blank=True, null=True)),
                ("reviews", models.IntegerField(default=0)),
                ("again", models.IntegerField(default=0)),
                ("mandatory_reviews", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "recall_chapterrollup",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("chapter_id__isnull", False)),
                        fields=("user_id", "local_date", "chapter_id"),
                        name="recall_chapterrollup_chapter_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("chapter_id__isnull", True)),
                        fields=("user_id", "local_date"),
                        name="recall_chapterrollup_unsorted_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecallReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_kind", models.CharField(max_length=8)),
                ("target_id", models.UUIDField()),
                ("item_version_id", models.UUIDField(blank=True, null=True)),
                ("reporter_user_id", models.UUIDField()),
                ("reason", models.CharField(max_length=12)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("status", models.CharField(default="open", max_length=10)),
                ("handled_by", models.UUIDField(blank=True, null=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "recall_report",
                "indexes": [
                    models.Index(fields=["status", "target_kind", "created_at"], name="recall_report_queue_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("target_kind__in", ["item", "share", "deck"])),
                        name="recall_report_target_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reason__in", ["wrong", "outdated", "copyright", "abusive", "spam", "other"])
                        ),
                        name="recall_report_reason_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["open", "actioned", "dismissed"])),
                        name="recall_report_status_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("reporter_user_id", "target_kind", "target_id"),
                        name="recall_report_one_open_per_reporter",
                    ),
                ],
            },
        ),
    ]
