/**
 * The only place icons are imported from. Apps import icons from '@artha/design-system', never from 'lucide-react'
 * directly (ESLint enforces this). Add an icon here when a screen needs it: one curated list keeps the bundle small
 * and the visual language consistent (Lucide: 24px grid, 2px stroke, rounded caps).
 *
 * Usage rules: decorative icons get aria-hidden (Lucide sets it when no aria-label is passed); icon-only buttons need an
 * aria-label on the button; size with `className="size-4"` (inside Button this is automatic); colour with text-* tokens.
 */
export type { LucideIcon, LucideProps } from 'lucide-react'
export {
  AlarmClock,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  Bell,
  BellRing,
  Bold,
  Bookmark,
  BookOpen,
  CalendarDays,
  CalendarRange,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clock,
  CloudOff,
  Code,
  Coffee,
  Columns2,
  Copy,
  Crop,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  FileClock,
  FileText,
  Flame,
  FolderInput,
  GraduationCap,
  Hash,
  Heading2,
  History,
  Hourglass,
  ImagePlus,
  Inbox,
  Info,
  Italic,
  Keyboard,
  KeyRound,
  Layers,
  List,
  ListChecks,
  ListFilter,
  ListOrdered,
  ListTodo,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  Maximize2,
  Menu,
  Merge,
  Minimize2,
  Moon,
  Notebook,
  NotebookPen,
  Palette,
  PartyPopper,
  Pause,
  Pencil,
  PictureInPicture2,
  Pin,
  PinOff,
  Play,
  Plus,
  Quote,
  RefreshCw,
  RotateCcw,
  Scissors,
  Search,
  Send,
  Settings,
  Share,
  ShieldCheck,
  Sigma,
  SkipForward,
  Smartphone,
  Sparkles,
  Square,
  SquareCheckBig,
  SquarePlus,
  StickyNote,
  Sun,
  SunMoon,
  Table,
  Tag,
  Target,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  Upload,
  UserRound,
  Volume2,
  VolumeX,
  WifiOff,
  X,
  Zap,
} from 'lucide-react'

/** Study Time Tracker icon: distinct from Flame, which means streaks. */
export { AlarmClock as StudyTimeIcon } from 'lucide-react'

/** Lucide's `Image` would shadow the DOM `Image` constructor, so it is exported as ImageIcon. */
export { Image as ImageIcon } from 'lucide-react'
