# Generated by Django 5.2.17 on 2026-10-04 10:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("full_name", models.CharField(blank=True, max_length=120)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "course",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ca", "Chartered Accountancy"),
                            ("cs", "Company Secretaryship"),
                            ("cma", "Cost and Management Accountancy"),
                        ],
                        max_length=8,
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=32)),
                ("exam_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "profiles",
            },
        ),
    ]
