# Generated by Django 5.2.17 on 2026-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("editor", "Editor"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
