# Generated by Django 5.2.17 on 2026-10-05 20:28

import uuid

from django.db import migrations, models

import modules.profiles.models


def lastvisit_fillfactor(apps, schema_editor):
    """Repeated updates of one row should be HOT (no indexed column changes), so leave room on each page."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE profiles_lastvisit SET (fillfactor = 70)")


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_profile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastVisit",
            fields=[
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=300)),
                ("search", models.CharField(blank=True, default="", max_length=200)),
                ("visited_at", models.DateTimeField()),
            ],
            options={
                "db_table": "profiles_lastvisit",
            },
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("completed_version", models.SmallIntegerField(default=0)),
                ("backfilled", models.BooleanField(default=False)),
                (
                    "current_step",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "steps",
                    models.JSONField(default=modules.profiles.models.default_onboarding_steps),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "profiles_onboarding",
            },
        ),
        migrations.CreateModel(
            name="StorageDelete",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("bucket", models.CharField(default="avatars", max_length=40)),
                ("path", models.CharField(max_length=200)),
                ("attempts", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "profiles_storagedelete",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_key",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_kind",
            field=models.CharField(
                choices=[
                    ("initials", "Initials"),
                    ("preset", "Preset"),
                    ("upload", "Upload"),
                ],
                default="initials",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_preset_key",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(("avatar_kind__in", ["initials", "preset", "upload"])),
                name="profiles_avatar_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("avatar_key", ""),
                        ("avatar_kind", "initials"),
                        ("avatar_preset_key", ""),
                    ),
                    models.Q(
                        ("avatar_key", ""),
                        ("avatar_kind", "preset"),
                        models.Q(("avatar_preset_key", ""), _negated=True),
                    ),
                    models.Q(
                        ("avatar_kind", "upload"),
                        ("avatar_preset_key", ""),
                        models.Q(("avatar_key", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="profiles_avatar_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="lastvisit",
            constraint=models.CheckConstraint(
                condition=models.Q(("path__startswith", "/app")),
                name="profiles_lastvisit_path_app",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboarding",
            constraint=models.CheckConstraint(
                condition=models.Q(("completed_version__gte", 0), ("completed_version__lte", 100)),
                name="profiles_onboarding_version_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboarding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", True), ("completed_version", 0)),
                    models.Q(("completed_at__isnull", False), ("completed_version__gt", 0)),
                    _connector="OR",
                ),
                name="profiles_onboarding_completed_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="storagedelete",
            index=models.Index(fields=["created_at"], name="profiles_sd_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="storagedelete",
            constraint=models.UniqueConstraint(fields=("bucket", "path"), name="profiles_storagedelete_unique"),
        ),
        migrations.RunPython(lastvisit_fillfactor, migrations.RunPython.noop),
    ]
