# Generated by Django 5.2.18 on 2026-10-07 17:50

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("dedupe_key", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("running", "Running"), ("done", "Done"), ("failed", "Failed")],
                        default="queued",
                        max_length=8,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                ("attempts", models.SmallIntegerField(default=0)),
                ("max_attempts", models.SmallIntegerField(default=5)),
                ("run_after", models.DateTimeField(default=django.utils.timezone.now)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, default="", max_length=64)),
                ("last_error", models.CharField(blank=True, default="", max_length=500)),
                ("result", models.JSONField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_job",
                "indexes": [models.Index(fields=["status", "-priority", "run_after"], name="core_job_claim_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key__isnull", False), ("status__in", ["queued", "running"])),
                        fields=("dedupe_key",),
                        name="core_job_dedupe_while_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["queued", "running", "done", "failed"])),
                        name="core_job_status_valid",
                    ),
                ],
            },
        ),
    ]
