# Generated by Django 5.2.18 on 2026-10-07 17:50

import uuid

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models

import modules.notes.domain.legend


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_code", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("max_storage_mb", models.IntegerField()),
                ("max_file_mb", models.IntegerField()),
                ("max_pages", models.IntegerField()),
                ("max_documents", models.IntegerField()),
                ("max_notes", models.IntegerField()),
                ("max_note_chars", models.IntegerField()),
                ("max_note_images", models.IntegerField()),
                ("max_marks_per_document", models.IntegerField()),
                ("max_tags", models.IntegerField()),
                ("ocr_pages_per_month", models.IntegerField()),
                ("ai_ocr_pages_per_month", models.IntegerField()),
                ("ai_summaries_per_month", models.IntegerField()),
                ("exports_per_month", models.IntegerField()),
                ("max_share_links", models.IntegerField()),
                ("max_offline_documents", models.IntegerField()),
            ],
            options={
                "db_table": "notes_quotaplan",
            },
        ),
        migrations.CreateModel(
            name="MonthlyUsage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField()),
                ("month", models.DateField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "month", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ocr_pages", models.IntegerField(default=0)),
                ("ai_ocr_pages", models.IntegerField(default=0)),
                ("ai_summaries", models.IntegerField(default=0)),
                ("exports", models.IntegerField(default=0)),
                ("uploads", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "notes_monthlyusage",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ai_ocr_pages__gte", 0),
                            ("ai_summaries__gte", 0),
                            ("ocr_pages__gte", 0),
                            ("exports__gte", 0),
                            ("uploads__gte", 0),
                        ),
                        name="notes_monthlyusage_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_key", models.CharField(blank=True, max_length=80, null=True)),
                ("chapter_key", models.CharField(blank=True, max_length=100, null=True)),
                ("topic_key", models.CharField(blank=True, max_length=120, null=True)),
                ("user_id", models.UUIDField()),
                ("client_id", models.UUIDField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("note", "Note"), ("exam_summary", "Exam summary")], default="note", max_length=12
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("typed", "Typed"),
                            ("clip", "Clip"),
                            ("ai_summary", "AI summary"),
                            ("import", "Import"),
                        ],
                        default="typed",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("body_md", models.TextField(blank=True, default="")),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_chars", models.IntegerField(default=0)),
                ("lang", models.CharField(default="en", max_length=5)),
                ("search_tsv", django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ("is_current_summary", models.BooleanField(default=False)),
                ("pinned", models.BooleanField(default=False)),
                ("clip_source", models.JSONField(blank=True, null=True)),
                ("clip_schema", models.SmallIntegerField(default=1)),
                ("ai_job_id", models.UUIDField(blank=True, null=True)),
                ("source_refs", models.JSONField(blank=True, null=True)),
                ("refs_schema", models.SmallIntegerField(default=1)),
                ("recall_card_id", models.UUIDField(blank=True, null=True)),
                ("rev", models.IntegerField(default=1)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("purge_after", models.DateTimeField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.chapter",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.level",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="syllabus.topic",
                    ),
                ),
            ],
            options={
                "db_table": "notes_note",
            },
        ),
        migrations.CreateModel(
            name="NoteImage",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "note_id", "attachment_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("alt_text", models.TextField(blank=True, default="")),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="media.attachment"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="notes.note"
                    ),
                ),
            ],
            options={
                "db_table": "notes_noteimage",
            },
        ),
        migrations.CreateModel(
            name="NoteVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("rev", models.IntegerField()),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("body_md", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("autosave", "Autosave"),
                            ("manual", "Manual"),
                            ("restore", "Restore"),
                            ("merge", "Merge"),
                            ("ai", "AI"),
                        ],
                        default="autosave",
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="notes.note"
                    ),
                ),
            ],
            options={
                "db_table": "notes_noteversion",
            },
        ),
        migrations.CreateModel(
            name="QuotaUsage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("bytes_used", models.BigIntegerField(default=0)),
                ("docs_active", models.IntegerField(default=0)),
                ("notes_active", models.IntegerField(default=0)),
                ("tags_count", models.IntegerField(default=0)),
                ("share_links_active", models.IntegerField(default=0)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notes_quotausage",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("bytes_used__gte", 0),
                            ("docs_active__gte", 0),
                            ("notes_active__gte", 0),
                            ("tags_count__gte", 0),
                            ("share_links_active__gte", 0),
                        ),
                        name="notes_quotausage_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("color_legend", models.JSONField(default=modules.notes.domain.legend.default_legend)),
                ("legend_schema", models.SmallIntegerField(default=1)),
                ("default_color", models.CharField(default="y", max_length=2)),
                ("page_tone", models.CharField(default="original", max_length=8)),
                ("finger_draws", models.BooleanField(default=False)),
                ("ocr_default", models.CharField(default="ask", max_length=6)),
                ("ocr_lang", models.CharField(default="eng", max_length=8)),
                ("ai_consent_version", models.CharField(blank=True, max_length=32, null=True)),
                ("ai_consent_at", models.DateTimeField(blank=True, null=True)),
                ("ai_consent_withdrawn_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notes_settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("page_tone__in", ["original", "paper", "night"])),
                        name="notes_settings_page_tone_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ocr_default__in", ["ask", "always", "never"])),
                        name="notes_settings_ocr_default_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ocr_lang__in", ["eng", "eng+hin"])), name="notes_settings_ocr_lang_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("default_color__in", ["y", "g", "b", "p", "o"])),
                        name="notes_settings_default_color_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("name", models.CharField(max_length=30)),
                ("name_norm", models.CharField(max_length=60)),
                ("color_key", models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                "db_table": "notes_tag",
                "constraints": [
                    models.UniqueConstraint(fields=("user_id", "name_norm"), name="notes_tag_user_name_unique"),
                    models.UniqueConstraint(fields=("id", "user_id"), name="notes_tag_id_user_unique"),
                    models.CheckConstraint(condition=models.Q(("name__regex", ".+")), name="notes_tag_name_not_empty"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_tags",
                        to="notes.note",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="notes.tag"
                    ),
                ),
            ],
            options={
                "db_table": "notes_itemtag",
            },
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["user_id", "-updated_at", "id"],
                name="notes_note_hub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["user_id", "level", "subject_key", "chapter_key", "-updated_at", "id"],
                name="notes_note_chapter_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=["user_id", "deleted_at"],
                name="notes_note_trash_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                condition=models.Q(("chapter__isnull", True), ("deleted_at__isnull", True)),
                fields=["user_id"],
                name="notes_note_unfiled_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)), fields=["purge_after"], name="notes_note_purge_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("chapter__isnull", True),
                    models.Q(("chapter_key__isnull", False), ("level__isnull", False), ("subject_key__isnull", False)),
                    _connector="OR",
                ),
                name="notes_note_chapter_has_keys",
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("topic__isnull", True),
                    models.Q(("chapter__isnull", False), ("topic_key__isnull", False)),
                    _connector="OR",
                ),
                name="notes_note_topic_has_chapter",
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(fields=("id", "user_id"), name="notes_note_id_user_unique"),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False)),
                fields=("user_id", "client_id"),
                name="notes_note_client_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("is_current_summary", True), ("kind", "exam_summary")
                ),
                fields=("user_id", "level", "subject_key", "chapter_key"),
                name="notes_note_one_current_summary",
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["note", "exam_summary"])), name="notes_note_kind_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin__in", ["typed", "clip", "ai_summary", "import"])),
                name="notes_note_origin_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind", "exam_summary"), ("is_current_summary", False), _connector="OR"),
                name="notes_note_summary_flag_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(("body_chars__gte", 0), ("body_chars__lte", 100000)), name="notes_note_body_chars"
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(condition=models.Q(("rev__gte", 1)), name="notes_note_rev_positive"),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(("lang__in", ["en", "hi", "mixed"])), name="notes_note_lang_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(("purge_after__isnull", True), ("deleted_at__isnull", False), _connector="OR"),
                name="notes_note_purge_needs_trash",
            ),
        ),
        migrations.AddIndex(
            model_name="noteimage",
            index=models.Index(fields=["attachment"], name="notes_noteimage_attachment_idx"),
        ),
        migrations.AddIndex(
            model_name="noteversion",
            index=models.Index(fields=["note", "-created_at"], name="notes_noteversion_note_idx"),
        ),
        migrations.AddIndex(
            model_name="noteversion",
            index=models.Index(fields=["created_at"], name="notes_noteversion_thin_idx"),
        ),
        migrations.AddConstraint(
            model_name="noteversion",
            constraint=models.UniqueConstraint(fields=("note", "rev"), name="notes_noteversion_note_rev_unique"),
        ),
        migrations.AddConstraint(
            model_name="noteversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["autosave", "manual", "restore", "merge", "ai"])),
                name="notes_noteversion_source_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="itemtag",
            index=models.Index(fields=["note"], name="notes_itemtag_note_idx"),
        ),
        migrations.AddConstraint(
            model_name="itemtag",
            constraint=models.CheckConstraint(
                condition=models.Q(("note__isnull", False)), name="notes_itemtag_one_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemtag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("note__isnull", False)),
                fields=("tag", "note"),
                name="notes_itemtag_tag_note_unique",
            ),
        ),
    ]
