# Generated by Django 5.2.18 on 2026-10-07 19:43

import uuid

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models

from core.migration_utils import composite_fks, postgres_only


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("notes", "0003_ownership_keys"),
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        # Needed by the page-range exclusion constraint (gist on uuid) and the page search index (gin on uuid).
        postgres_only(["CREATE EXTENSION IF NOT EXISTS btree_gin", "CREATE EXTENSION IF NOT EXISTS btree_gist"]),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_key", models.CharField(blank=True, max_length=80, null=True)),
                ("chapter_key", models.CharField(blank=True, max_length=100, null=True)),
                ("topic_key", models.CharField(blank=True, max_length=120, null=True)),
                ("user_id", models.UUIDField()),
                ("client_id", models.UUIDField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[("upload", "Upload"), ("platform", "Platform")], default="upload", max_length=8
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("bytes", models.BigIntegerField()),
                ("page_count", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("scanning", "Scanning"),
                            ("inspecting", "Inspecting"),
                            ("ready", "Ready"),
                            ("needs_password", "Needs password"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="reserved",
                        max_length=14,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("institute_material", "Institute material"),
                            ("coaching", "Coaching"),
                            ("own_notes", "Own notes"),
                            ("handwritten", "Handwritten"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("edition_label", models.CharField(blank=True, max_length=40, null=True)),
                ("ocr_mode", models.CharField(default="none", max_length=9)),
                ("ocr_lang", models.CharField(default="eng", max_length=8)),
                ("last_page", models.IntegerField(default=1)),
                ("last_zoom", models.CharField(default="fit", max_length=8)),
                ("page_tone", models.CharField(blank=True, max_length=8, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("change_seq", models.BigIntegerField(default=0)),
                ("marks_count", models.IntegerField(default=0)),
                ("reservation_expires_at", models.DateTimeField(blank=True, null=True)),
                ("rev", models.IntegerField(default=1)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("purge_after", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notes_document",
            },
        ),
        migrations.CreateModel(
            name="DocumentChapter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_key", models.CharField(blank=True, max_length=80, null=True)),
                ("chapter_key", models.CharField(blank=True, max_length=100, null=True)),
                ("topic_key", models.CharField(blank=True, max_length=120, null=True)),
                ("user_id", models.UUIDField()),
                ("page_from", models.IntegerField()),
                ("page_to", models.IntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[("user", "User"), ("outline", "Outline"), ("ai", "AI")], default="user", max_length=7
                    ),
                ),
            ],
            options={
                "db_table": "notes_documentchapter",
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(choices=[("pdf", "PDF"), ("archive", "Archive")], default="pdf", max_length=7),
                ),
                ("client_id", models.UUIDField(blank=True, null=True)),
                ("options", models.JSONField(default=dict)),
                ("options_schema", models.SmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="queued",
                        max_length=7,
                    ),
                ),
                ("progress", models.SmallIntegerField(default=0)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=20, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notes_exportjob",
            },
        ),
        migrations.CreateModel(
            name="FileContent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("bytes", models.BigIntegerField()),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("page_meta", models.JSONField(blank=True, null=True)),
                ("page_meta_schema", models.SmallIntegerField(default=1)),
                ("outline", models.JSONField(blank=True, null=True)),
                ("outline_schema", models.SmallIntegerField(default=1)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("can_copy", models.BooleanField(blank=True, null=True)),
                ("can_modify", models.BooleanField(blank=True, null=True)),
                ("has_javascript", models.BooleanField(default=False)),
                ("is_scanned", models.BooleanField(blank=True, null=True)),
                ("text_pct", models.SmallIntegerField(blank=True, null=True)),
                (
                    "text_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("locked", "Locked"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("text_pages_done", models.IntegerField(default=0)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("partial", "Partial"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                ("ocr_engine", models.CharField(blank=True, max_length=40, null=True)),
                ("ocr_pages_done", models.IntegerField(default=0)),
                ("ocr_pages_total", models.IntegerField(default=0)),
                ("ocr_avg_conf", models.SmallIntegerField(blank=True, null=True)),
                ("engine_version", models.SmallIntegerField(default=1)),
                ("orphaned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notes_filecontent",
            },
        ),
        migrations.CreateModel(
            name="FilePage",
            fields=[
                ("page", models.IntegerField()),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="notes.filecontent"
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "content_id", "page", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "text_source",
                    models.CharField(
                        choices=[("native", "Native"), ("ocr", "OCR"), ("ai", "AI")], default="native", max_length=6
                    ),
                ),
                ("ocr_conf", models.SmallIntegerField(blank=True, null=True)),
                ("words", models.JSONField(blank=True, null=True)),
                ("words_schema", models.SmallIntegerField(default=1)),
                ("lang", models.CharField(default="en", max_length=5)),
                ("tsv", django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notes_filepage",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="attachment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="+", to="media.attachment"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.chapter",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="cover_attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="media.attachment",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.level",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.subject",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.topic",
            ),
        ),
        migrations.AddField(
            model_name="documentchapter",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.chapter",
            ),
        ),
        migrations.AddField(
            model_name="documentchapter",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ranges", to="notes.document"
            ),
        ),
        migrations.AddField(
            model_name="documentchapter",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.level",
            ),
        ),
        migrations.AddField(
            model_name="documentchapter",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.subject",
            ),
        ),
        migrations.AddField(
            model_name="documentchapter",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.topic",
            ),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="media.attachment",
            ),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exports",
                to="notes.document",
            ),
        ),
        migrations.AddIndex(
            model_name="filecontent",
            index=models.Index(
                condition=models.Q(("text_status__in", ["pending", "running"])),
                fields=["text_status"],
                name="notes_fc_text_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filecontent",
            index=models.Index(
                condition=models.Q(("ocr_status__in", ["pending", "running", "partial"])),
                fields=["ocr_status"],
                name="notes_fc_ocr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filecontent",
            index=models.Index(
                condition=models.Q(("orphaned_at__isnull", False)), fields=["orphaned_at"], name="notes_fc_orphan_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="filecontent",
            constraint=models.CheckConstraint(condition=models.Q(("bytes__gte", 0)), name="notes_filecontent_bytes"),
        ),
        migrations.AddConstraint(
            model_name="filecontent",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_status__in", ["pending", "running", "done", "failed", "locked", "skipped"])),
                name="notes_filecontent_text_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="filecontent",
            constraint=models.CheckConstraint(
                condition=models.Q(("ocr_status__in", ["none", "pending", "running", "partial", "done", "failed"])),
                name="notes_filecontent_ocr_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="filecontent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("text_pct__isnull", True), models.Q(("text_pct__gte", 0), ("text_pct__lte", 100)), _connector="OR"
                ),
                name="notes_filecontent_text_pct",
            ),
        ),
        migrations.AddConstraint(
            model_name="filecontent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ocr_avg_conf__isnull", True),
                    models.Q(("ocr_avg_conf__gte", 0), ("ocr_avg_conf__lte", 100)),
                    _connector="OR",
                ),
                name="notes_filecontent_ocr_conf",
            ),
        ),
        migrations.AddConstraint(
            model_name="filecontent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ocr_pages_done__gte", 0), ("ocr_pages_total__gte", 0), ("text_pages_done__gte", 0)
                ),
                name="notes_filecontent_progress_nonnegative",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="notes.filecontent",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchapter",
            index=models.Index(fields=["document", "page_from"], name="notes_documentchapter_doc_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentchapter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("chapter__isnull", True),
                    models.Q(("chapter_key__isnull", False), ("level__isnull", False), ("subject_key__isnull", False)),
                    _connector="OR",
                ),
                name="notes_documentchapter_chapter_has_keys",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchapter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("topic__isnull", True),
                    models.Q(("chapter__isnull", False), ("topic_key__isnull", False)),
                    _connector="OR",
                ),
                name="notes_documentchapter_topic_has_chapter",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchapter",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_from__gte", 1), ("page_to__gte", models.F("page_from"))),
                name="notes_documentchapter_pages",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchapter",
            constraint=models.CheckConstraint(
                condition=models.Q(("chapter__isnull", False)), name="notes_documentchapter_chapter_required"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchapter",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["user", "outline", "ai"])), name="notes_documentchapter_source_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["user_id", "-created_at"], name="notes_exportjob_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=["status", "updated_at"],
                name="notes_exportjob_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="notes_exportjob_expiry_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False)),
                fields=("user_id", "client_id"),
                name="notes_exportjob_client_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["pdf", "archive"])), name="notes_exportjob_kind_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind", "archive"), ("document__isnull", False), _connector="OR"),
                name="notes_exportjob_pdf_has_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["queued", "running", "done", "failed", "expired"])),
                name="notes_exportjob_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("progress__gte", 0), ("progress__lte", 100)), name="notes_exportjob_progress"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("error_code__isnull", True),
                    ("error_code__in", ["export_too_large", "restricted", "locked", "failed"]),
                    _connector="OR",
                ),
                name="notes_exportjob_error_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["user_id", "deleted_at", "-last_opened_at"], name="notes_document_library_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["user_id", "level", "subject_key", "chapter_key"],
                name="notes_document_subject_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["content"], name="notes_document_content_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("status__in", ["reserved", "scanning", "inspecting"])),
                fields=["status", "updated_at"],
                name="notes_document_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=["purge_after"],
                name="notes_document_purge_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("chapter__isnull", True),
                    models.Q(("chapter_key__isnull", False), ("level__isnull", False), ("subject_key__isnull", False)),
                    _connector="OR",
                ),
                name="notes_document_chapter_has_keys",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("topic__isnull", True),
                    models.Q(("chapter__isnull", False), ("topic_key__isnull", False)),
                    _connector="OR",
                ),
                name="notes_document_topic_has_chapter",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(fields=("id", "user_id"), name="notes_document_id_user_unique"),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False)),
                fields=("user_id", "client_id"),
                name="notes_document_client_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin__in", ["upload", "platform"])), name="notes_document_origin_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "reserved",
                            "scanning",
                            "inspecting",
                            "ready",
                            "needs_password",
                            "rejected",
                            "expired",
                            "failed",
                        ],
                    )
                ),
                name="notes_document_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status_reason__isnull", True),
                    (
                        "status_reason__in",
                        [
                            "type_mismatch",
                            "malware",
                            "pdf_corrupt",
                            "too_many_pages",
                            "too_large",
                            "decode_failed",
                            "policy",
                        ],
                    ),
                    _connector="OR",
                ),
                name="notes_document_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_kind__in", ["institute_material", "coaching", "own_notes", "handwritten", "other"])
                ),
                name="notes_document_source_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("ocr_mode__in", ["none", "tesseract", "ai"])), name="notes_document_ocr_mode_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("ocr_lang__in", ["eng", "eng+hin"])), name="notes_document_ocr_lang_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("page_tone__isnull", True), ("page_tone__in", ["original", "paper", "night"]), _connector="OR"
                ),
                name="notes_document_page_tone_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("bytes__gte", 0)), name="notes_document_bytes_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("marks_count__gte", 0), ("marks_count__lte", 20000)),
                name="notes_document_marks_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin", "upload"), ("bytes", 0), _connector="OR"),
                name="notes_document_platform_has_no_bytes",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_page__gte", 1), ("rev__gte", 1)), name="notes_document_rev_page_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("purge_after__isnull", True), ("deleted_at__isnull", False), _connector="OR"),
                name="notes_document_purge_needs_trash",
            ),
        ),
        migrations.AddConstraint(
            model_name="filepage",
            constraint=models.CheckConstraint(
                condition=models.Q(("page__gte", 1)), name="notes_filepage_page_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="filepage",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_source__in", ["native", "ocr", "ai"])), name="notes_filepage_source_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="filepage",
            constraint=models.CheckConstraint(
                condition=models.Q(("lang__in", ["en", "hi", "mixed"])), name="notes_filepage_lang_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="filepage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ocr_conf__isnull", True), models.Q(("ocr_conf__gte", 0), ("ocr_conf__lte", 100)), _connector="OR"
                ),
                name="notes_filepage_conf",
            ),
        ),
        # PostgreSQL-only DDL Django cannot declare (see core.migration_utils).
        composite_fks(
            (
                "notes_documentchapter",
                "notes_documentchapter_document_user_fk",
                ("document_id", "user_id"),
                "notes_document",
                ("id", "user_id"),
            ),
            (
                "notes_exportjob",
                "notes_exportjob_document_user_fk",
                ("document_id", "user_id"),
                "notes_document",
                ("id", "user_id"),
            ),
        ),
        # Ranges of one document cannot overlap: the database refuses it (ERD 2.7).
        postgres_only(
            [
                "ALTER TABLE notes_documentchapter ADD CONSTRAINT notes_documentchapter_no_overlap "
                "EXCLUDE USING gist (document_id WITH =, int4range(page_from, page_to, '[]') WITH &&)"
            ],
            ["ALTER TABLE notes_documentchapter DROP CONSTRAINT IF EXISTS notes_documentchapter_no_overlap"],
        ),
        # "Pages of these documents matching this query" in one index (ERD 2.3).
        postgres_only(
            ["CREATE INDEX notes_filepage_search_idx ON notes_filepage USING gin (content_id, tsv)"],
            ["DROP INDEX IF EXISTS notes_filepage_search_idx"],
        ),
    ]
