# Generated by Django 5.2.18 on 2026-10-07 19:43

import uuid

import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models

from core.migration_utils import composite_fks


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("notes", "0004_documents"),
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_key", models.CharField(blank=True, max_length=80, null=True)),
                ("chapter_key", models.CharField(blank=True, max_length=100, null=True)),
                ("topic_key", models.CharField(blank=True, max_length=120, null=True)),
                ("user_id", models.UUIDField()),
                ("page", models.IntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("highlight", "Highlight"),
                            ("underline", "Underline"),
                            ("ink", "Ink"),
                            ("textbox", "Text box"),
                            ("sticky", "Sticky note"),
                            ("bookmark", "Bookmark"),
                            ("area", "Area"),
                        ],
                        max_length=9,
                    ),
                ),
                ("geometry", models.JSONField()),
                ("geometry_schema", models.SmallIntegerField(default=1)),
                ("color", models.CharField(blank=True, max_length=2, null=True)),
                ("comment", models.TextField(blank=True, default="")),
                ("quote_exact", models.TextField(blank=True, null=True)),
                ("quote_prefix", models.CharField(blank=True, max_length=32, null=True)),
                ("quote_suffix", models.CharField(blank=True, max_length=32, null=True)),
                ("text_start", models.IntegerField(blank=True, null=True)),
                ("text_end", models.IntegerField(blank=True, null=True)),
                ("anchor_engine", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "chapter_source",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicit"),
                            ("range", "Range"),
                            ("document", "Document"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                ("search_tsv", django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ("recall_card_id", models.UUIDField(blank=True, null=True)),
                ("rev", models.IntegerField(default=1)),
                ("seq", models.BigIntegerField()),
                ("device_id", models.CharField(blank=True, max_length=36, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("purge_after", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notes_annotation",
            },
        ),
        migrations.RemoveConstraint(
            model_name="itemtag",
            name="notes_itemtag_one_target",
        ),
        migrations.AddField(
            model_name="annotation",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.chapter",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.level",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.subject",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="syllabus.topic",
            ),
        ),
        migrations.AddField(
            model_name="itemtag",
            name="annotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_tags",
                to="notes.annotation",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="annotations", to="notes.document"
            ),
        ),
        migrations.AddField(
            model_name="itemtag",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_tags",
                to="notes.document",
            ),
        ),
        migrations.AddIndex(
            model_name="itemtag",
            index=models.Index(fields=["annotation"], name="notes_itemtag_annotation_idx"),
        ),
        migrations.AddIndex(
            model_name="itemtag",
            index=models.Index(fields=["document"], name="notes_itemtag_document_idx"),
        ),
        migrations.AddConstraint(
            model_name="itemtag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("annotation__isnull", True), ("document__isnull", True), ("note__isnull", False)),
                    models.Q(("annotation__isnull", False), ("document__isnull", True), ("note__isnull", True)),
                    models.Q(("annotation__isnull", True), ("document__isnull", False), ("note__isnull", True)),
                    _connector="OR",
                ),
                name="notes_itemtag_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemtag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("annotation__isnull", False)),
                fields=("tag", "annotation"),
                name="notes_itemtag_tag_annotation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemtag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", False)),
                fields=("tag", "document"),
                name="notes_itemtag_tag_document_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(fields=["document", "seq"], name="notes_annotation_delta_idx"),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["document", "page"],
                name="notes_annotation_page_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("kind__in", ["highlight", "underline", "area", "sticky", "textbox"])
                ),
                fields=["user_id", "level", "subject_key", "chapter_key", "-updated_at", "id"],
                name="notes_annotation_chapter_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=["user_id", "deleted_at"],
                name="notes_annotation_trash_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=["purge_after"],
                name="notes_annotation_purge_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("chapter__isnull", True),
                    models.Q(("chapter_key__isnull", False), ("level__isnull", False), ("subject_key__isnull", False)),
                    _connector="OR",
                ),
                name="notes_annotation_chapter_has_keys",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("topic__isnull", True),
                    models.Q(("chapter__isnull", False), ("topic_key__isnull", False)),
                    _connector="OR",
                ),
                name="notes_annotation_topic_has_chapter",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(fields=("id", "user_id"), name="notes_annotation_id_user_unique"),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("page__gte", 1), ("page__lte", 5000)), name="notes_annotation_page"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["highlight", "underline", "ink", "textbox", "sticky", "bookmark", "area"])
                ),
                name="notes_annotation_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.LessThanOrEqual(
                    django.db.models.functions.text.Length(
                        django.db.models.functions.comparison.Cast("geometry", models.TextField())
                    ),
                    65536,
                ),
                name="notes_annotation_geometry_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("color__isnull", True),
                    ("color__in", ["y", "g", "b", "p", "o", "i1", "i2", "i3", "i4", "i5"]),
                    _connector="OR",
                ),
                name="notes_annotation_color_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.LessThanOrEqual(
                    django.db.models.functions.text.Length("comment"), 2000
                ),
                name="notes_annotation_comment_length",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.LessThanOrEqual(
                    django.db.models.functions.text.Length("quote_exact"), 1000
                ),
                name="notes_annotation_quote_length",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("anchor_engine__isnull", True), ("anchor_engine__in", ["pdfjs", "ocr"]), _connector="OR"
                ),
                name="notes_annotation_anchor_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("chapter_source__in", ["explicit", "range", "document", "none"])),
                name="notes_annotation_chapter_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("rev__gte", 1)), name="notes_annotation_rev_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("purge_after__isnull", True), ("deleted_at__isnull", False), _connector="OR"),
                name="notes_annotation_purge_needs_deleted",
            ),
        ),
        composite_fks(
            (
                "notes_annotation",
                "notes_annotation_document_user_fk",
                ("document_id", "user_id"),
                "notes_document",
                ("id", "user_id"),
            ),
            (
                "notes_itemtag",
                "notes_itemtag_annotation_user_fk",
                ("annotation_id", "user_id"),
                "notes_annotation",
                ("id", "user_id"),
            ),
            (
                "notes_itemtag",
                "notes_itemtag_document_user_fk",
                ("document_id", "user_id"),
                "notes_document",
                ("id", "user_id"),
            ),
        ),
    ]
