# Generated by Django 5.2.18 on 2026-10-08 11:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_annotations_and_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("client_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("exam_summary", "Exam summary"), ("ocr_page_ai", "AI page reading")], max_length=12
                    ),
                ),
                ("scope", models.JSONField(default=dict)),
                ("scope_schema", models.SmallIntegerField(default=1)),
                ("input_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("accepted", "Accepted"),
                            ("discarded", "Discarded"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("budget_blocked", "Budget blocked"),
                        ],
                        default="queued",
                        max_length=14,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=64, null=True)),
                ("prompt_version", models.CharField(blank=True, max_length=32, null=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cost_paise", models.IntegerField(default=0)),
                ("item_count", models.IntegerField(default=0)),
                ("result_md", models.TextField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("result_note_id", models.UUIDField(blank=True, null=True)),
                ("charged", models.BooleanField(default=True)),
                ("error_code", models.CharField(blank=True, max_length=20, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notes_aijob",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status__in", ["ready", "accepted"])),
                        fields=["user_id", "kind", "input_hash", "-created_at"],
                        name="notes_aijob_cache_idx",
                    ),
                    models.Index(
                        condition=models.Q(("status__in", ["queued", "running"])),
                        fields=["status", "created_at"],
                        name="notes_aijob_active_idx",
                    ),
                    models.Index(fields=["user_id", "-created_at"], name="notes_aijob_owner_idx"),
                    models.Index(
                        condition=models.Q(("status", "ready")), fields=["expires_at"], name="notes_aijob_expiry_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user_id", "client_id"), name="notes_aijob_client_id_unique"),
                    models.UniqueConstraint(fields=("id", "user_id"), name="notes_aijob_id_user_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["exam_summary", "ocr_page_ai"])), name="notes_aijob_kind_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "queued",
                                    "running",
                                    "ready",
                                    "accepted",
                                    "discarded",
                                    "expired",
                                    "failed",
                                    "cancelled",
                                    "budget_blocked",
                                ],
                            )
                        ),
                        name="notes_aijob_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("error_code__isnull", True),
                            (
                                "error_code__in",
                                ["budget", "model_error", "blocked", "too_little", "consent_withdrawn", "unavailable"],
                            ),
                            _connector="OR",
                        ),
                        name="notes_aijob_error_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cost_paise__gte", 0),
                            ("input_tokens__gte", 0),
                            ("item_count__gte", 0),
                            ("output_tokens__gte", 0),
                        ),
                        name="notes_aijob_nonnegative",
                    ),
                ],
            },
        ),
    ]
