# Generated by Django 5.2.18 on 2026-10-08 12:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("notes", "0006_ai_jobs"),
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReanchorItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("source_annotation_id", models.UUIDField()),
                ("kind", models.CharField(max_length=9)),
                ("page", models.IntegerField()),
                ("color", models.CharField(blank=True, max_length=2, null=True)),
                ("quote_exact", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, default="")),
                ("geometry", models.JSONField()),
                ("reason", models.CharField(max_length=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("kept", "Kept"),
                            ("noted", "Saved as a note"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=9,
                    ),
                ),
                ("new_annotation_id", models.UUIDField(blank=True, null=True)),
                ("result_note_id", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notes_reanchoritem",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="reanchor_stats",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="reanchor_status",
            field=models.CharField(default="none", max_length=8),
        ),
        migrations.AddField(
            model_name="document",
            name="replaces_document_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("reanchor_status__in", ["none", "waiting", "running", "done", "failed"])),
                name="notes_document_reanchor_valid",
            ),
        ),
        migrations.AddField(
            model_name="reanchoritem",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reanchor_items", to="notes.document"
            ),
        ),
        migrations.AddIndex(
            model_name="reanchoritem",
            index=models.Index(fields=["document", "status", "page"], name="notes_reanchoritem_doc_idx"),
        ),
        migrations.AddConstraint(
            model_name="reanchoritem",
            constraint=models.UniqueConstraint(
                fields=("document", "source_annotation_id"), name="notes_reanchoritem_source_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="reanchoritem",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "kept", "noted", "dismissed"])),
                name="notes_reanchoritem_status_valid",
            ),
        ),
    ]
