# Generated by Django 5.2.18 on 2026-10-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("notes", "0007_replace_edition"),
        ("syllabus", "0009_chaptermap_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="unlock_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="unlock_failures",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="unlock_reason",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="unlock_status",
            field=models.CharField(default="none", max_length=8),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("unlock_status__in", ["none", "waiting", "running", "done", "failed"])),
                name="notes_document_unlock_valid",
            ),
        ),
    ]
