# Generated by Django 5.2.18 on 2026-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0008_unlock_for_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="resumable_upload_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
