"""
The attachment kinds notes stores (F-03 ERD 3.3, 6.6), registered with `media` at app start. Quota stays here: the kind's
`reserve` and `release` call the atomic statements in `services.quota`, so `media` never learns what a plan is.

    note_image   png, jpeg, webp up to 5 MB (R1). Goes through the scan pipeline like every upload: with the null scanner
                 (development, tests) it is clean at completion, with ClamAV a `media.scan` job decides.
    note_pdf     a student's PDF, `application/pdf` only, up to the plan's `max_file_mb`. Reserving it takes bytes AND a document
                 slot in one statement (`quota.reserve_document`). The first kilobyte must be a PDF header (`media.sniff`), then
                 ClamAV; a clean file queues `notes.inspect`, a rejected one marks its document `rejected`.
    note_export  a flattened PDF or the whole-account zip, built by the worker, kept 7 days. Never counts against storage (its
                 own limit is `exports_per_month`) and the browser cannot upload it.

Where a PDF lives: uploads first land under `quarantine/{user}/{attachment}.pdf` (ERD 6.6) and the object STAYS there for its
whole life. The path in `media_attachment` is the source of truth and the bucket is private, so a file is reachable only by a
signed URL issued after the owner check on a `clean` row; moving it on `clean` would add a copy-and-delete that can half fail
for no security gain. "Quarantine" therefore names where uploads land, not a state: whether a file may be used is the row's
`status`. Ids only in paths, never a file name or a title.
"""

from __future__ import annotations

import uuid

from modules.media import sniff
from modules.media.registry import KindSpec

from . import media_hooks
from .services import quota

BUCKET = "notes-private"
NOTES_FLAG = "notes"
PDF_FLAG = "notes_pdf"
NOTE_IMAGE_MIMES = frozenset({"image/png", "image/jpeg", "image/webp"})
NOTE_IMAGE_MAX_BYTES = 5 * 1024 * 1024
PDF_MIME = "application/pdf"
ZIP_MIME = "application/zip"
EXPORT_MAX_BYTES = 1024 * 1024 * 1024
EXPORT_RETENTION_DAYS = 7
_EXTENSION = {"image/png": "png", "image/jpeg": "jpg", "image/webp": "webp", PDF_MIME: "pdf", ZIP_MIME: "zip"}


def _image_path(user_id: str, attachment_id: uuid.UUID, mime: str) -> str:
    """`{user}/notes/images/{attachment}.{ext}`: ids only, never a file name or a note title."""
    return f"{user_id}/notes/images/{attachment_id}.{_EXTENSION[mime]}"


def _pdf_path(user_id: str, attachment_id: uuid.UUID, mime: str) -> str:
    """`quarantine/{user}/{attachment}.pdf`: where uploads land, and where the object stays (see the module doc)."""
    return f"quarantine/{user_id}/{attachment_id}.pdf"


def _export_path(user_id: str, attachment_id: uuid.UUID, mime: str) -> str:
    return f"{user_id}/exports/{attachment_id}.{_EXTENSION[mime]}"


def _no_quota(user_id: str, amount: int) -> None:
    """Exports are temporary and limited per month, not by storage."""


NOTE_IMAGE = KindSpec(
    name="note_image",
    bucket=BUCKET,
    mimes=NOTE_IMAGE_MIMES,
    max_bytes=lambda user_id: NOTE_IMAGE_MAX_BYTES,
    reserve=quota.reserve_bytes,
    release=quota.release_bytes,
    path_for=_image_path,
    scan="clamav",
    flag=NOTES_FLAG,
)

NOTE_PDF = KindSpec(
    name="note_pdf",
    bucket=BUCKET,
    mimes=frozenset({PDF_MIME}),
    max_bytes=lambda user_id: quota.limits_for(user_id).file_bytes,
    reserve=quota.reserve_document,
    release=quota.release_document,
    path_for=_pdf_path,
    on_clean=media_hooks.pdf_clean,
    on_reject=media_hooks.pdf_rejected,
    sniff=sniff.pdf_sniff,
    sniff_bytes=sniff.PDF_SNIFF_BYTES,
    scan="clamav",
    flag=PDF_FLAG,
    public=False,  # `POST notes/documents/` reserves the document row and the file together
    read_url_seconds=4 * 3600,  # the reader keeps the URL for a long session (ERD 6.6)
)

NOTE_EXPORT = KindSpec(
    name="note_export",
    bucket=BUCKET,
    mimes=frozenset({PDF_MIME, ZIP_MIME}),
    max_bytes=lambda user_id: EXPORT_MAX_BYTES,
    reserve=_no_quota,
    release=_no_quota,
    path_for=_export_path,
    scan="none",  # generated by us from files that were already scanned
    flag=PDF_FLAG,
    public=False,
    retention_days=EXPORT_RETENTION_DAYS,
    read_url_seconds=24 * 3600,
)
